/**
 * SPL Token Forwarder PA Integration Tests
 *
 * These tests verify the full PA settlement flow with SPL Token Forwarder:
 * - Wrap: Ed25519 signature verification + token transfer to escrow
 * - Unwrap: Escrow release to recipient
 *
 * Uses fixtures generated by fixture-gen with embedded external call data.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  PublicKey,
  SystemProgram,
  Keypair,
  ComputeBudgetProgram,
  SYSVAR_CLOCK_PUBKEY,
  SYSVAR_INSTRUCTIONS_PUBKEY,
  Ed25519Program,
  TransactionInstruction,
  Transaction,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  createMint,
  getOrCreateAssociatedTokenAccount,
  mintTo,
  approve,
  getAccount,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { assert } from "chai";
import { existsSync } from "fs";
import path from "path";
import bs58 from "bs58";
import { SolanaPaPrototype } from "../target/types/solana_pa_prototype";
import { SplTokenForwarder } from "../target/types/spl_token_forwarder";
import {
  VERIFIER_ROUTER_ID,
  GROTH16_VERIFIER_ID,
} from "../scripts/verifier-utils";
import {
  PA_STATE_SEED,
  NULLIFIER_SEED,
  TX_DATA_SEED,
  ROOT_MARKER_SEED,
  EMPTY_TREE_ROOT_INITIAL,
} from "./utils";
import {
  derivePaStatePda,
  deriveRootMarkerPda,
  deriveConfigPda as deriveForwarderConfigPda,
  deriveEscrowPda,
  deriveNonceBitmapPda,
  parseSelectorFromFixture,
  deriveRouterAccounts,
} from "./utils";
import { readJson, Fixture } from "./utils";
import { airdrop, drainKeypairs, createWrapMessageHash } from "./utils";

describe("SPL Token Forwarder PA Integration", function () {
  // Increase timeout for fixture-based tests
  this.timeout(120000);

  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const localFundedKeypairs: Keypair[] = [];
  async function localAirdrop(kp: Keypair, sol: number) {
    await airdrop(provider, kp, sol);
    localFundedKeypairs.push(kp);
  }

  const paProgram = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;
  const forwarderProgram = anchor.workspace.SplTokenForwarder as Program<SplTokenForwarder>;

  const groth16VerifierId = GROTH16_VERIFIER_ID;
  const verifierRouterId = VERIFIER_ROUTER_ID;

  const [paState] = derivePaStatePda(paProgram.programId);

  // Thin wrappers that bind program IDs from the closure
  function localDeriveRootMarkerPda(root: Buffer): PublicKey {
    return deriveRootMarkerPda(paState, root, paProgram.programId);
  }

  function localDeriveEscrowPda(tokenMint: PublicKey): [PublicKey, number] {
    return deriveEscrowPda(forwarderProgram.programId, tokenMint);
  }

  function localDeriveNonceBitmapPda(user: PublicKey, nonce: bigint): [PublicKey, number] {
    return deriveNonceBitmapPda(forwarderProgram.programId, user, nonce);
  }

  // Check if fixtures exist before running tests
  const wrapFixturePath = path.resolve(process.cwd(), "tests", "fixtures", "spl_token_wrap.json");
  const unwrapFixturePath = path.resolve(process.cwd(), "tests", "fixtures", "spl_token_unwrap.json");
  const wrapFixtureExists = existsSync(wrapFixturePath);
  const unwrapFixtureExists = existsSync(unwrapFixturePath);

  // Shared state
  let routerPda: PublicKey;
  let verifierEntryPda: PublicKey;
  let genesisRootMarkerPda: PublicKey;
  let forwarderConfigPda: PublicKey;
  let emergencyCommittee: Keypair;

  before(async () => {
    // Skip if no fixtures (they take ~30min to generate)
    if (!wrapFixtureExists && !unwrapFixtureExists) {
      console.log("    ⚠ No SPL Token Forwarder fixtures found. Skipping PA integration tests.");
      console.log("    Run fixture-gen with --spl-token-wrap and --spl-token-unwrap to generate.");
      return;
    }

    // Use wrap fixture for setup (or unwrap if wrap doesn't exist)
    const fixture = readJson<Fixture>(wrapFixtureExists ? wrapFixturePath : unwrapFixturePath);
    const GROTH16_SELECTOR = parseSelectorFromFixture(fixture.selector);

    // Derive PDAs
    const accounts = deriveRouterAccounts(verifierRouterId, GROTH16_SELECTOR);
    routerPda = accounts.routerPda;
    verifierEntryPda = accounts.verifierEntryPda;

    // Initialize PA state if needed
    const genesisRoot = EMPTY_TREE_ROOT_INITIAL;
    genesisRootMarkerPda = localDeriveRootMarkerPda(genesisRoot);

    try {
      await paProgram.account.paStateAccount.fetch(paState);
    } catch {
      await paProgram.methods
        .initialize()
        .accounts({
          paState,
          payer: provider.wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .remainingAccounts([
          { pubkey: genesisRootMarkerPda, isWritable: true, isSigner: false },
        ])
        .rpc();
    }

    // Initialize forwarder config if needed
    [forwarderConfigPda] = deriveForwarderConfigPda(forwarderProgram.programId);
    emergencyCommittee = Keypair.generate();
    await localAirdrop(emergencyCommittee, 1);

    try {
      await forwarderProgram.account.config.fetch(forwarderConfigPda);
    } catch {
      // Get logic_ref from fixture
      const logicRefB64 = fixture.spl_token_wrap?.logic_ref_b64 || fixture.spl_token_unwrap?.logic_ref_b64;
      if (!logicRefB64) {
        throw new Error("No logic_ref found in fixture metadata");
      }
      const logicRef = Array.from(Buffer.from(logicRefB64, "base64"));

      await forwarderProgram.methods
        .initialize(paProgram.programId, logicRef, emergencyCommittee.publicKey)
        .accounts({
          authority: provider.wallet.publicKey,
          config: forwarderConfigPda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();
    }
  });

  // Helper to settle via TxData
  async function settleViaTxData(
    authority: Keypair,
    fixture: Fixture,
    forwarderAccounts: { pubkey: PublicKey; isWritable: boolean; isSigner: boolean }[],
    preInstructions?: TransactionInstruction[],
    options?: { newRootMarkerPda?: PublicKey }
  ) {
    const payload = Buffer.from(fixture.tx_b64, "base64");
    const GROTH16_SELECTOR = parseSelectorFromFixture(fixture.selector);
    const { routerPda, verifierEntryPda } = deriveRouterAccounts(verifierRouterId, GROTH16_SELECTOR);

    await localAirdrop(authority, 2);

    const uploadId = new anchor.BN(Date.now());
    const uploadIdLe = Buffer.alloc(8);
    uploadIdLe.writeBigUInt64LE(BigInt(uploadId.toString()));

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      paProgram.programId
    );

    const capacity = payload.length;
    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    await paProgram.methods
      .txdataInit(uploadId, capacity, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    const chunkSize = 700;
    for (let offset = 0; offset < payload.length; offset += chunkSize) {
      const chunk = payload.subarray(offset, Math.min(payload.length, offset + chunkSize));
      await paProgram.methods
        .txdataWrite(uploadId, offset, Buffer.from(chunk))
        .accounts({
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
    }

    // Nullifier PDAs
    const nullifierPdas = fixture.consumed_nullifiers_b64.map((nfB64) => {
      const nf = Buffer.from(nfB64, "base64");
      return PublicKey.findProgramAddressSync(
        [NULLIFIER_SEED, paState.toBuffer(), nf],
        paProgram.programId
      )[0];
    });

    const nullifierAccounts = nullifierPdas.map((pubkey) => ({
      pubkey,
      isWritable: true,
      isSigner: false,
    }));

    // Build remaining accounts: nullifiers + forwarder accounts + new root marker
    const allRemainingAccounts = [...nullifierAccounts, ...forwarderAccounts];

    if (options?.newRootMarkerPda) {
      allRemainingAccounts.push({
        pubkey: options.newRootMarkerPda,
        isWritable: true,
        isSigner: false,
      });
    }

    // IMPORTANT: Ed25519 instruction must be at index 0 to match fixture's ed25519_ix_index
    // ComputeBudget comes after to avoid shifting instruction indices
    const allPreInstructions = [
      ...(preInstructions || []),
      ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
      ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
    ];

    return paProgram.methods
      .settleFromTxdata(uploadId)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
        verifierRouterProgram: verifierRouterId,
        router: routerPda,
        verifierEntry: verifierEntryPda,
        verifierProgram: groth16VerifierId,
      })
      .remainingAccounts(allRemainingAccounts)
      .preInstructions(allPreInstructions)
      .signers([authority])
      .rpc();
  }

  // ==========================================================================
  // Wrap PA Integration Tests
  // ==========================================================================

  describe("Wrap PA Integration", function () {
    // Skip if no wrap fixture
    before(function () {
      if (!wrapFixtureExists) {
        console.log("    ⚠ spl_token_wrap.json not found, skipping wrap tests");
        this.skip();
      }
    });

    // Mirrors: test_wrap_pulls_funds_from_user (via PA settlement)
    // https://github.com/anoma/anomapay-backend/blob/main/contracts/test/ERC20Forwarder.t.sol
    it("settles wrap through PA with Ed25519 signature verification", async function () {
      if (!wrapFixtureExists) this.skip();

      const fixture = readJson<Fixture>(wrapFixturePath);
      const metadata = fixture.spl_token_wrap!;

      // Decode test data from fixture
      const userSecretKey = Buffer.from(metadata.user_secret_key_b64, "base64");
      const userPubkey = new PublicKey(Buffer.from(metadata.user_pubkey_b64, "base64"));
      const mintSeed = Buffer.from(metadata.mint_seed_b64, "base64");
      const amount = BigInt(metadata.amount);
      const nonce = BigInt(metadata.nonce);
      const deadline = BigInt(metadata.deadline);
      const actionTreeRoot = Buffer.from(metadata.action_tree_root_b64, "base64");
      const signature = Buffer.from(metadata.signature_b64, "base64");

      // Create deterministic keypairs from fixture seeds
      const userKeypair = Keypair.fromSeed(userSecretKey);
      const mintKeypair = Keypair.fromSeed(mintSeed);
      assert.ok(
        userKeypair.publicKey.equals(userPubkey),
        "Derived user pubkey should match fixture"
      );
      // Verify mint pubkey matches fixture (sanity check)
      const expectedMint = new PublicKey(bs58.decode(metadata.token_mint_b58));
      assert.ok(
        mintKeypair.publicKey.equals(expectedMint),
        "Derived mint pubkey should match fixture"
      );

      // Airdrop for fees
      await localAirdrop(userKeypair, 2);

      // Create deterministic mint using the keypair from fixture
      // The 6th argument to createMint is the mint keypair
      const mint = await createMint(
        provider.connection,
        userKeypair, // payer
        userKeypair.publicKey, // mint authority
        null, // freeze authority
        6, // decimals
        mintKeypair // deterministic mint keypair
      );
      assert.ok(mint.equals(expectedMint), "Created mint should match fixture");

      // Create user ATA and mint tokens
      const userAta = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        userKeypair,
        mint,
        userPubkey
      );
      await mintTo(
        provider.connection,
        userKeypair,
        mint,
        userAta.address,
        userKeypair, // mint authority
        Number(amount) * 2
      );

      // Create escrow ATA (must exist before wrap)
      const [escrowPda] = localDeriveEscrowPda(mint);
      const escrowAtaAccount = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        userKeypair,
        mint,
        escrowPda,
        true // allowOwnerOffCurve - required for PDA owners
      );
      const escrowAta = escrowAtaAccount.address;

      // Approve forwarder's escrow as delegate
      await approve(
        provider.connection,
        userKeypair,
        userAta.address,
        escrowPda,
        userPubkey,
        Number(amount)
      );

      // Nonce bitmap PDA (Permit2-style: each PDA stores 256 nonces)
      const [nonceBitmapPda] = localDeriveNonceBitmapPda(userPubkey, nonce);

      // Create Ed25519 verify instruction with the fixture's signature
      // The signature was computed over: SHA256(forwarder_id || mint || amount || nonce || deadline || action_tree_root)
      const messageHash = createWrapMessageHash(
        forwarderProgram.programId,
        mint,
        amount,
        nonce,
        deadline,
        actionTreeRoot
      );
      const ed25519Ix = Ed25519Program.createInstructionWithPublicKey({
        publicKey: userPubkey.toBytes(),
        message: messageHash,
        signature: signature,
      });

      // Authority that will upload TxData and pay for nonce bitmap creation
      const authority = Keypair.generate();

      // Forwarder accounts for CPI
      // Order: forwarder_program (segment marker) | config | ix_sysvar | clock | ...remaining
      // CPI caller verification uses instruction introspection (no caller account needed).
      // Remaining accounts order: user_ata, escrow_ata, escrow_pda, nonce_bitmap, token_program, system_program, payer, mint
      const forwarderAccounts = [
        { pubkey: forwarderProgram.programId, isWritable: false, isSigner: false },
        { pubkey: forwarderConfigPda, isWritable: false, isSigner: false },
        { pubkey: SYSVAR_INSTRUCTIONS_PUBKEY, isWritable: false, isSigner: false },
        { pubkey: SYSVAR_CLOCK_PUBKEY, isWritable: false, isSigner: false },
        { pubkey: userAta.address, isWritable: true, isSigner: false },
        { pubkey: escrowAta, isWritable: true, isSigner: false },
        { pubkey: escrowPda, isWritable: false, isSigner: false },
        { pubkey: nonceBitmapPda, isWritable: true, isSigner: false },
        { pubkey: TOKEN_PROGRAM_ID, isWritable: false, isSigner: false },
        { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
        { pubkey: authority.publicKey, isWritable: true, isSigner: false }, // payer for nonce bitmap
        { pubkey: mint, isWritable: false, isSigner: false },
      ];

      // Record balances before
      const userBalanceBefore = (await getAccount(provider.connection, userAta.address)).amount;

      await settleViaTxData(authority, fixture, forwarderAccounts, [ed25519Ix]);

      // Verify tokens were transferred to escrow
      const userBalanceAfter = (await getAccount(provider.connection, userAta.address)).amount;
      const escrowBalance = (await getAccount(provider.connection, escrowAta)).amount;

      assert.equal(
        userBalanceAfter.toString(),
        (userBalanceBefore - amount).toString(),
        "User balance should decrease by wrap amount"
      );
      assert.equal(
        escrowBalance.toString(),
        amount.toString(),
        "Escrow should hold wrapped tokens"
      );
    });
  });

  // ==========================================================================
  // Unwrap PA Integration Tests
  // ==========================================================================

  describe("Unwrap PA Integration", function () {
    before(function () {
      if (!unwrapFixtureExists) {
        console.log("    ⚠ spl_token_unwrap.json not found, skipping unwrap tests");
        this.skip();
      }
    });

    // Mirrors: test_unwrap_sends_funds_to_the_user (via PA settlement)
    // https://github.com/anoma/anomapay-backend/blob/main/contracts/test/ERC20Forwarder.t.sol
    it("settles unwrap through PA (escrow release)", async function () {
      if (!unwrapFixtureExists) this.skip();

      const fixture = readJson<Fixture>(unwrapFixturePath);
      const metadata = fixture.spl_token_unwrap!;

      // Decode test data from fixture
      const mintSeed = Buffer.from(metadata.mint_seed_b64, "base64");
      const recipientSeed = Buffer.from(metadata.recipient_seed_b64, "base64");
      const amount = BigInt(metadata.amount);

      // Create deterministic keypairs from fixture seeds
      const mintKeypair = Keypair.fromSeed(mintSeed);
      const recipientKeypair = Keypair.fromSeed(recipientSeed);

      // Verify derived pubkeys match fixture (sanity check)
      const expectedMint = new PublicKey(bs58.decode(metadata.token_mint_b58));
      const expectedRecipient = new PublicKey(bs58.decode(metadata.recipient_b58));
      assert.ok(
        mintKeypair.publicKey.equals(expectedMint),
        "Derived mint pubkey should match fixture"
      );
      assert.ok(
        recipientKeypair.publicKey.equals(expectedRecipient),
        "Derived recipient pubkey should match fixture"
      );

      // Airdrop for fees
      await localAirdrop(recipientKeypair, 2);

      // Create deterministic mint using the keypair from fixture
      // Check if mint already exists (may have been created by wrap test running first)
      let mint: PublicKey;
      const mintInfo = await provider.connection.getAccountInfo(expectedMint);
      if (mintInfo) {
        // Mint already exists (created by wrap test)
        mint = expectedMint;
      } else {
        // Create the mint
        mint = await createMint(
          provider.connection,
          recipientKeypair, // payer
          recipientKeypair.publicKey, // mint authority
          null, // freeze authority
          6, // decimals
          mintKeypair // deterministic mint keypair
        );
        assert.ok(mint.equals(expectedMint), "Created mint should match fixture");
      }

      // Create escrow ATA and fund it (simulating prior wraps)
      const [escrowPda] = localDeriveEscrowPda(mint);
      const escrowAta = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        recipientKeypair,
        mint,
        escrowPda,
        true
      );

      // Only mint to escrow if it doesn't have enough tokens
      // (If wrap test ran first, escrow already has tokens and we're not the mint authority)
      if (escrowAta.amount < amount) {
        if (!mintInfo) {
          // We created the mint, so we're the authority - mint tokens
          await mintTo(
            provider.connection,
            recipientKeypair,
            mint,
            escrowAta.address,
            recipientKeypair, // mint authority
            Number(amount) * 2
          );
        } else {
          // Mint was created by wrap test - skip minting and use existing escrow balance
          // The wrap test should have deposited tokens to escrow
          assert.fail("Escrow doesn't have enough tokens and we can't mint (wrap test didn't run or failed)");
        }
      }

      // Create recipient ATA
      const recipientAta = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        recipientKeypair,
        mint,
        recipientKeypair.publicKey
      );

      // Forwarder accounts for CPI
      // Order: forwarder_program (segment marker) | config | ix_sysvar | clock | ...remaining
      const forwarderAccounts = [
        { pubkey: forwarderProgram.programId, isWritable: false, isSigner: false },
        { pubkey: forwarderConfigPda, isWritable: false, isSigner: false },
        { pubkey: SYSVAR_INSTRUCTIONS_PUBKEY, isWritable: false, isSigner: false },
        { pubkey: SYSVAR_CLOCK_PUBKEY, isWritable: false, isSigner: false },
        { pubkey: escrowAta.address, isWritable: true, isSigner: false },
        { pubkey: recipientAta.address, isWritable: true, isSigner: false },
        { pubkey: escrowPda, isWritable: false, isSigner: false },
        { pubkey: TOKEN_PROGRAM_ID, isWritable: false, isSigner: false },
        { pubkey: mint, isWritable: false, isSigner: false },
      ];

      // Record balances before
      const escrowBalanceBefore = (await getAccount(provider.connection, escrowAta.address)).amount;
      const recipientBalanceBefore = (await getAccount(provider.connection, recipientAta.address)).amount;

      const authority = Keypair.generate();
      await settleViaTxData(authority, fixture, forwarderAccounts);

      // Verify tokens were transferred from escrow to recipient
      const escrowBalanceAfter = (await getAccount(provider.connection, escrowAta.address)).amount;
      const recipientBalanceAfter = (await getAccount(provider.connection, recipientAta.address)).amount;

      assert.equal(
        escrowBalanceAfter.toString(),
        (escrowBalanceBefore - amount).toString(),
        "Escrow balance should decrease by unwrap amount"
      );
      assert.equal(
        recipientBalanceAfter.toString(),
        (recipientBalanceBefore + amount).toString(),
        "Recipient should receive unwrapped tokens"
      );
    });
  });

  // Drain funded keypairs back to the provider wallet so devnet SOL isn't lost.
  after(async () => {
    await drainKeypairs(provider, localFundedKeypairs, "02-forwarder-pa");
    localFundedKeypairs.length = 0;
  });
});
