/**
 * SPL Token Forwarder PA Integration Tests
 *
 * These tests verify the full PA settlement flow with SPL Token Forwarder:
 * - Wrap: Ed25519 signature verification + token transfer to escrow
 * - Unwrap: Escrow release to recipient
 *
 * Uses fixtures generated by fixture-gen with embedded external call data.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  PublicKey,
  SystemProgram,
  Keypair,
  LAMPORTS_PER_SOL,
  ComputeBudgetProgram,
  SYSVAR_CLOCK_PUBKEY,
  SYSVAR_INSTRUCTIONS_PUBKEY,
  Ed25519Program,
  TransactionInstruction,
} from "@solana/web3.js";
import {
  createMint,
  getOrCreateAssociatedTokenAccount,
  mintTo,
  approve,
  getAccount,
  TOKEN_PROGRAM_ID,
  getAssociatedTokenAddressSync,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { assert } from "chai";
import { readFileSync, existsSync } from "fs";
import path from "path";
import bs58 from "bs58";
import { SolanaPaPrototype } from "../target/types/solana_pa_prototype";
import { SplTokenForwarder } from "../target/types/spl_token_forwarder";
import { address } from "@solana/kit";
import {
  getRouterPda,
  getVerifierEntryPda,
} from "../../risc0-solana/solana-verifier/scripts/utils/utils";

// Fixture types
type SplTokenWrapMetadata = {
  user_secret_key_b64: string;
  user_pubkey_b64: string;
  mint_seed_b64: string;
  token_mint_b58: string;
  amount: number;
  nonce: number;
  deadline: number;
  action_tree_root_b64: string;
  signature_b64: string;
  logic_ref_b64: string;
};

type SplTokenUnwrapMetadata = {
  mint_seed_b64: string;
  token_mint_b58: string;
  amount: number;
  recipient_seed_b64: string;
  recipient_b58: string;
  logic_ref_b64: string;
};

type Fixture = {
  format: string;
  aggregation_strategy: string;
  aggregation_proof_type: string;
  selector: string;
  forwarder_type: string;
  tx_b64: string;
  tx_tampered_b64: string;
  consumed_nullifiers_b64: string[];
  spl_token_wrap?: SplTokenWrapMetadata;
  spl_token_unwrap?: SplTokenUnwrapMetadata;
};

function readJson<T>(filePath: string): T {
  return JSON.parse(readFileSync(filePath, "utf8")) as T;
}

function programIdFromKeypairFile(keypairPath: string): PublicKey {
  const secret = Uint8Array.from(readJson<number[]>(keypairPath));
  return Keypair.fromSecretKey(secret).publicKey;
}

async function airdrop(provider: anchor.AnchorProvider, to: PublicKey, sol: number) {
  const sig = await provider.connection.requestAirdrop(to, sol * LAMPORTS_PER_SOL);
  await provider.connection.confirmTransaction(sig, "confirmed");
}

function parseSelectorFromFixture(selectorHex: string): Buffer {
  const hex = selectorHex.replace(/^0x/, "");
  if (hex.length !== 8) {
    throw new Error(`Invalid selector format: ${selectorHex} (expected 8 hex chars)`);
  }
  return Buffer.from(hex, "hex");
}

async function deriveRouterAccounts(
  verifierRouterId: PublicKey,
  selector: Buffer
): Promise<{ routerPda: PublicKey; verifierEntryPda: PublicKey }> {
  const routerAddr = address(verifierRouterId.toBase58());
  const routerPdaInfo = await getRouterPda(routerAddr);
  const verifierEntryPdaInfo = await getVerifierEntryPda(routerAddr, selector);
  return {
    routerPda: new PublicKey(routerPdaInfo.address),
    verifierEntryPda: new PublicKey(verifierEntryPdaInfo.address),
  };
}

// PDA seeds
const PA_STATE_SEED = Buffer.from("pa_state");
const NULLIFIER_SEED = Buffer.from("nullifier");
const TX_DATA_SEED = Buffer.from("tx_data");
const ROOT_MARKER_SEED = Buffer.from("root");
const CONFIG_SEED = Buffer.from("config");
const ESCROW_SEED = Buffer.from("escrow");
const NONCE_BITMAP_SEED = Buffer.from("nonce_bitmap");
const NONCES_PER_WORD = 256n;

// Genesis root for depth-1 tree
const EMPTY_TREE_ROOT_INITIAL = Buffer.from(
  "cc1d2f838445db7aec431df9ee8a871f40e7aa5e064fc056633ef8c60fab7b06",
  "hex"
);

describe("SPL Token Forwarder PA Integration", function () {
  // Increase timeout for fixture-based tests
  this.timeout(120000);

  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const paProgram = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;
  const forwarderProgram = anchor.workspace.SplTokenForwarder as Program<SplTokenForwarder>;

  // Load groth16 verifier program ID
  const groth16KeypairPath = path.resolve(
    process.cwd(),
    "..",
    "risc0-solana",
    "solana-verifier",
    "target",
    "deploy",
    "groth_16_verifier-keypair.json"
  );
  const groth16VerifierId = programIdFromKeypairFile(groth16KeypairPath);

  // Load verifier_router program ID
  const routerKeypairPath = path.resolve(
    process.cwd(),
    "..",
    "risc0-solana",
    "solana-verifier",
    "target",
    "deploy",
    "verifier_router-keypair.json"
  );
  const verifierRouterId = programIdFromKeypairFile(routerKeypairPath);

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], paProgram.programId);

  function deriveRootMarkerPda(root: Buffer): PublicKey {
    return PublicKey.findProgramAddressSync(
      [ROOT_MARKER_SEED, paState.toBuffer(), root],
      paProgram.programId
    )[0];
  }

  function computeGenesisRoot(): Buffer {
    return EMPTY_TREE_ROOT_INITIAL;
  }

  // Forwarder PDA helpers
  function deriveForwarderConfigPda(): [PublicKey, number] {
    return PublicKey.findProgramAddressSync([CONFIG_SEED], forwarderProgram.programId);
  }

  function deriveEscrowPda(tokenMint: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [ESCROW_SEED, tokenMint.toBuffer()],
      forwarderProgram.programId
    );
  }

  function deriveNonceBitmapPda(user: PublicKey, nonce: bigint): [PublicKey, number] {
    // Permit2-style bitmap pattern: each PDA stores 256 nonces
    // Word index = nonce / 256
    const wordIndex = nonce / NONCES_PER_WORD;
    const wordIndexBuffer = Buffer.alloc(8);
    wordIndexBuffer.writeBigUInt64LE(wordIndex);
    return PublicKey.findProgramAddressSync(
      [NONCE_BITMAP_SEED, user.toBuffer(), wordIndexBuffer],
      forwarderProgram.programId
    );
  }

  // Check if fixtures exist before running tests
  const wrapFixturePath = path.resolve(process.cwd(), "tests", "fixtures", "spl_token_wrap.json");
  const unwrapFixturePath = path.resolve(process.cwd(), "tests", "fixtures", "spl_token_unwrap.json");
  const wrapFixtureExists = existsSync(wrapFixturePath);
  const unwrapFixtureExists = existsSync(unwrapFixturePath);

  // Shared state
  let routerPda: PublicKey;
  let verifierEntryPda: PublicKey;
  let genesisRootMarkerPda: PublicKey;
  let forwarderConfigPda: PublicKey;
  let emergencyCommittee: Keypair;

  before(async () => {
    // Skip if no fixtures (they take ~30min to generate)
    if (!wrapFixtureExists && !unwrapFixtureExists) {
      console.log("    ⚠ No SPL Token Forwarder fixtures found. Skipping PA integration tests.");
      console.log("    Run fixture-gen with --spl-token-wrap and --spl-token-unwrap to generate.");
      return;
    }

    // Use wrap fixture for setup (or unwrap if wrap doesn't exist)
    const fixture = readJson<Fixture>(wrapFixtureExists ? wrapFixturePath : unwrapFixturePath);
    const GROTH16_SELECTOR = parseSelectorFromFixture(fixture.selector);

    // Derive PDAs
    const accounts = await deriveRouterAccounts(verifierRouterId, GROTH16_SELECTOR);
    routerPda = accounts.routerPda;
    verifierEntryPda = accounts.verifierEntryPda;

    // Initialize PA state if needed
    const genesisRoot = computeGenesisRoot();
    genesisRootMarkerPda = deriveRootMarkerPda(genesisRoot);

    try {
      await paProgram.account.paStateAccount.fetch(paState);
    } catch {
      await paProgram.methods
        .initialize()
        .accounts({
          paState,
          payer: provider.wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .remainingAccounts([
          { pubkey: genesisRootMarkerPda, isWritable: true, isSigner: false },
        ])
        .rpc();
    }

    // Initialize forwarder config if needed
    [forwarderConfigPda] = deriveForwarderConfigPda();
    emergencyCommittee = Keypair.generate();
    await airdrop(provider, emergencyCommittee.publicKey, 1);

    try {
      await forwarderProgram.account.config.fetch(forwarderConfigPda);
    } catch {
      // Get logic_ref from fixture
      const logicRefB64 = fixture.spl_token_wrap?.logic_ref_b64 || fixture.spl_token_unwrap?.logic_ref_b64;
      if (!logicRefB64) {
        throw new Error("No logic_ref found in fixture metadata");
      }
      const logicRef = Array.from(Buffer.from(logicRefB64, "base64"));

      await forwarderProgram.methods
        .initialize(paProgram.programId, logicRef, emergencyCommittee.publicKey)
        .accounts({
          authority: provider.wallet.publicKey,
          config: forwarderConfigPda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();
    }
  });

  // Helper to settle via TxData
  async function settleViaTxData(
    authority: Keypair,
    fixture: Fixture,
    forwarderAccounts: { pubkey: PublicKey; isWritable: boolean; isSigner: boolean }[],
    preInstructions?: TransactionInstruction[],
    options?: { newRootMarkerPda?: PublicKey }
  ) {
    const payload = Buffer.from(fixture.tx_b64, "base64");
    const GROTH16_SELECTOR = parseSelectorFromFixture(fixture.selector);
    const { routerPda, verifierEntryPda } = await deriveRouterAccounts(verifierRouterId, GROTH16_SELECTOR);

    await airdrop(provider, authority.publicKey, 2);

    const uploadId = new anchor.BN(Date.now());
    const uploadIdLe = Buffer.alloc(8);
    uploadIdLe.writeBigUInt64LE(BigInt(uploadId.toString()));

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      paProgram.programId
    );

    const capacity = payload.length;
    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    await paProgram.methods
      .txdataInit(uploadId, capacity, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    const chunkSize = 700;
    for (let offset = 0; offset < payload.length; offset += chunkSize) {
      const chunk = payload.subarray(offset, Math.min(payload.length, offset + chunkSize));
      await paProgram.methods
        .txdataWrite(uploadId, offset, Buffer.from(chunk))
        .accounts({
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
    }

    // Nullifier PDAs
    const nullifierPdas = fixture.consumed_nullifiers_b64.map((nfB64) => {
      const nf = Buffer.from(nfB64, "base64");
      return PublicKey.findProgramAddressSync(
        [NULLIFIER_SEED, paState.toBuffer(), nf],
        paProgram.programId
      )[0];
    });

    const nullifierAccounts = nullifierPdas.map((pubkey) => ({
      pubkey,
      isWritable: true,
      isSigner: false,
    }));

    // Build remaining accounts: nullifiers + forwarder accounts + new root marker
    const allRemainingAccounts = [...nullifierAccounts, ...forwarderAccounts];

    if (options?.newRootMarkerPda) {
      allRemainingAccounts.push({
        pubkey: options.newRootMarkerPda,
        isWritable: true,
        isSigner: false,
      });
    }

    // IMPORTANT: Ed25519 instruction must be at index 0 to match fixture's ed25519_ix_index
    // ComputeBudget comes after to avoid shifting instruction indices
    const allPreInstructions = [
      ...(preInstructions || []),
      ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
    ];

    return paProgram.methods
      .settleFromTxdata(uploadId)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
        verifierRouterProgram: verifierRouterId,
        router: routerPda,
        verifierEntry: verifierEntryPda,
        verifierProgram: groth16VerifierId,
      })
      .remainingAccounts(allRemainingAccounts)
      .preInstructions(allPreInstructions)
      .signers([authority])
      .rpc();
  }

  // ==========================================================================
  // Wrap PA Integration Tests
  // ==========================================================================

  describe("Wrap PA Integration", function () {
    // Skip if no wrap fixture
    before(function () {
      if (!wrapFixtureExists) {
        console.log("    ⚠ spl_token_wrap.json not found, skipping wrap tests");
        this.skip();
      }
    });

    // Mirrors: test_wrap_pulls_funds_from_user (via PA settlement)
    // https://github.com/anoma/anomapay-backend/blob/main/contracts/test/ERC20Forwarder.t.sol
    it("settles wrap through PA with Ed25519 signature verification", async function () {
      if (!wrapFixtureExists) this.skip();

      const fixture = readJson<Fixture>(wrapFixturePath);
      const metadata = fixture.spl_token_wrap!;

      // Decode test data from fixture
      const userSecretKey = Buffer.from(metadata.user_secret_key_b64, "base64");
      const userPubkey = new PublicKey(Buffer.from(metadata.user_pubkey_b64, "base64"));
      const mintSeed = Buffer.from(metadata.mint_seed_b64, "base64");
      const amount = BigInt(metadata.amount);
      const nonce = BigInt(metadata.nonce);
      const deadline = BigInt(metadata.deadline);
      const actionTreeRoot = Buffer.from(metadata.action_tree_root_b64, "base64");
      const signature = Buffer.from(metadata.signature_b64, "base64");

      // Create deterministic keypairs from fixture seeds
      const userKeypair = Keypair.fromSeed(userSecretKey);
      const mintKeypair = Keypair.fromSeed(mintSeed);
      assert.ok(
        userKeypair.publicKey.equals(userPubkey),
        "Derived user pubkey should match fixture"
      );
      // Verify mint pubkey matches fixture (sanity check)
      const expectedMint = new PublicKey(bs58.decode(metadata.token_mint_b58));
      assert.ok(
        mintKeypair.publicKey.equals(expectedMint),
        "Derived mint pubkey should match fixture"
      );

      // Airdrop for fees
      await airdrop(provider, userPubkey, 2);

      // Create deterministic mint using the keypair from fixture
      // The 6th argument to createMint is the mint keypair
      const mint = await createMint(
        provider.connection,
        userKeypair, // payer
        userKeypair.publicKey, // mint authority
        null, // freeze authority
        6, // decimals
        mintKeypair // deterministic mint keypair
      );
      assert.ok(mint.equals(expectedMint), "Created mint should match fixture");

      // Create user ATA and mint tokens
      const userAta = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        userKeypair,
        mint,
        userPubkey
      );
      await mintTo(
        provider.connection,
        userKeypair,
        mint,
        userAta.address,
        userKeypair, // mint authority
        Number(amount) * 2
      );

      // Create escrow ATA (must exist before wrap)
      const [escrowPda] = deriveEscrowPda(mint);
      const escrowAtaAccount = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        userKeypair,
        mint,
        escrowPda,
        true // allowOwnerOffCurve - required for PDA owners
      );
      const escrowAta = escrowAtaAccount.address;

      // Approve forwarder's escrow as delegate
      await approve(
        provider.connection,
        userKeypair,
        userAta.address,
        escrowPda,
        userPubkey,
        Number(amount)
      );

      // Nonce bitmap PDA (Permit2-style: each PDA stores 256 nonces)
      const [nonceBitmapPda] = deriveNonceBitmapPda(userPubkey, nonce);

      // Create Ed25519 verify instruction with the fixture's signature
      // The signature was computed over: SHA256(forwarder_id || mint || amount || nonce || deadline || action_tree_root)
      const messageHash = createWrapMessageHash(
        forwarderProgram.programId,
        mint,
        amount,
        nonce,
        deadline,
        actionTreeRoot
      );
      const ed25519Ix = Ed25519Program.createInstructionWithPublicKey({
        publicKey: userPubkey.toBytes(),
        message: messageHash,
        signature: signature,
      });

      // Authority that will upload TxData and pay for nonce bitmap creation
      const authority = Keypair.generate();

      // Forwarder accounts for CPI
      // Order: forwarder_program (segment marker) | caller | config | ix_sysvar | clock | ...remaining
      // The PA strips the forwarder_program and passes the rest to the forwarder's instruction
      // Remaining accounts order: user_ata, escrow_ata, escrow_pda, nonce_bitmap, token_program, system_program, payer, mint
      const forwarderAccounts = [
        { pubkey: forwarderProgram.programId, isWritable: false, isSigner: false },
        { pubkey: paProgram.programId, isWritable: false, isSigner: false }, // caller (must match config.protocol_adapter)
        { pubkey: forwarderConfigPda, isWritable: false, isSigner: false },
        { pubkey: SYSVAR_INSTRUCTIONS_PUBKEY, isWritable: false, isSigner: false },
        { pubkey: SYSVAR_CLOCK_PUBKEY, isWritable: false, isSigner: false },
        { pubkey: userAta.address, isWritable: true, isSigner: false },
        { pubkey: escrowAta, isWritable: true, isSigner: false },
        { pubkey: escrowPda, isWritable: false, isSigner: false },
        { pubkey: nonceBitmapPda, isWritable: true, isSigner: false },
        { pubkey: TOKEN_PROGRAM_ID, isWritable: false, isSigner: false },
        { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
        { pubkey: authority.publicKey, isWritable: true, isSigner: false }, // payer for nonce bitmap
        { pubkey: mint, isWritable: false, isSigner: false },
      ];

      // Record balances before
      const userBalanceBefore = (await getAccount(provider.connection, userAta.address)).amount;

      await settleViaTxData(authority, fixture, forwarderAccounts, [ed25519Ix]);

      // Verify tokens were transferred to escrow
      const userBalanceAfter = (await getAccount(provider.connection, userAta.address)).amount;
      const escrowBalance = (await getAccount(provider.connection, escrowAta)).amount;

      assert.equal(
        userBalanceAfter.toString(),
        (userBalanceBefore - amount).toString(),
        "User balance should decrease by wrap amount"
      );
      assert.equal(
        escrowBalance.toString(),
        amount.toString(),
        "Escrow should hold wrapped tokens"
      );
    });
  });

  // ==========================================================================
  // Unwrap PA Integration Tests
  // ==========================================================================

  describe("Unwrap PA Integration", function () {
    before(function () {
      if (!unwrapFixtureExists) {
        console.log("    ⚠ spl_token_unwrap.json not found, skipping unwrap tests");
        this.skip();
      }
    });

    // Mirrors: test_unwrap_sends_funds_to_the_user (via PA settlement)
    // https://github.com/anoma/anomapay-backend/blob/main/contracts/test/ERC20Forwarder.t.sol
    it("settles unwrap through PA (escrow release)", async function () {
      if (!unwrapFixtureExists) this.skip();

      const fixture = readJson<Fixture>(unwrapFixturePath);
      const metadata = fixture.spl_token_unwrap!;

      // Decode test data from fixture
      const mintSeed = Buffer.from(metadata.mint_seed_b64, "base64");
      const recipientSeed = Buffer.from(metadata.recipient_seed_b64, "base64");
      const amount = BigInt(metadata.amount);

      // Create deterministic keypairs from fixture seeds
      const mintKeypair = Keypair.fromSeed(mintSeed);
      const recipientKeypair = Keypair.fromSeed(recipientSeed);

      // Verify derived pubkeys match fixture (sanity check)
      const expectedMint = new PublicKey(bs58.decode(metadata.token_mint_b58));
      const expectedRecipient = new PublicKey(bs58.decode(metadata.recipient_b58));
      assert.ok(
        mintKeypair.publicKey.equals(expectedMint),
        "Derived mint pubkey should match fixture"
      );
      assert.ok(
        recipientKeypair.publicKey.equals(expectedRecipient),
        "Derived recipient pubkey should match fixture"
      );

      // Airdrop for fees
      await airdrop(provider, recipientKeypair.publicKey, 2);

      // Create deterministic mint using the keypair from fixture
      // Check if mint already exists (may have been created by wrap test running first)
      let mint: PublicKey;
      const mintInfo = await provider.connection.getAccountInfo(expectedMint);
      if (mintInfo) {
        // Mint already exists (created by wrap test)
        mint = expectedMint;
      } else {
        // Create the mint
        mint = await createMint(
          provider.connection,
          recipientKeypair, // payer
          recipientKeypair.publicKey, // mint authority
          null, // freeze authority
          6, // decimals
          mintKeypair // deterministic mint keypair
        );
        assert.ok(mint.equals(expectedMint), "Created mint should match fixture");
      }

      // Create escrow ATA and fund it (simulating prior wraps)
      const [escrowPda] = deriveEscrowPda(mint);
      const escrowAta = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        recipientKeypair,
        mint,
        escrowPda,
        true
      );

      // Only mint to escrow if it doesn't have enough tokens
      // (If wrap test ran first, escrow already has tokens and we're not the mint authority)
      if (escrowAta.amount < amount) {
        if (!mintInfo) {
          // We created the mint, so we're the authority - mint tokens
          await mintTo(
            provider.connection,
            recipientKeypair,
            mint,
            escrowAta.address,
            recipientKeypair, // mint authority
            Number(amount) * 2
          );
        } else {
          // Mint was created by wrap test - skip minting and use existing escrow balance
          // The wrap test should have deposited tokens to escrow
          assert.fail("Escrow doesn't have enough tokens and we can't mint (wrap test didn't run or failed)");
        }
      }

      // Create recipient ATA
      const recipientAta = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        recipientKeypair,
        mint,
        recipientKeypair.publicKey
      );

      // Forwarder accounts for CPI
      // Order: forwarder_program (segment marker) | caller | config | ix_sysvar | clock | ...remaining
      const forwarderAccounts = [
        { pubkey: forwarderProgram.programId, isWritable: false, isSigner: false },
        { pubkey: paProgram.programId, isWritable: false, isSigner: false }, // caller (must match config.protocol_adapter)
        { pubkey: forwarderConfigPda, isWritable: false, isSigner: false },
        { pubkey: SYSVAR_INSTRUCTIONS_PUBKEY, isWritable: false, isSigner: false },
        { pubkey: SYSVAR_CLOCK_PUBKEY, isWritable: false, isSigner: false },
        { pubkey: escrowAta.address, isWritable: true, isSigner: false },
        { pubkey: recipientAta.address, isWritable: true, isSigner: false },
        { pubkey: escrowPda, isWritable: false, isSigner: false },
        { pubkey: TOKEN_PROGRAM_ID, isWritable: false, isSigner: false },
        { pubkey: mint, isWritable: false, isSigner: false },
      ];

      // Record balances before
      const escrowBalanceBefore = (await getAccount(provider.connection, escrowAta.address)).amount;
      const recipientBalanceBefore = (await getAccount(provider.connection, recipientAta.address)).amount;

      const authority = Keypair.generate();
      await settleViaTxData(authority, fixture, forwarderAccounts);

      // Verify tokens were transferred from escrow to recipient
      const escrowBalanceAfter = (await getAccount(provider.connection, escrowAta.address)).amount;
      const recipientBalanceAfter = (await getAccount(provider.connection, recipientAta.address)).amount;

      assert.equal(
        escrowBalanceAfter.toString(),
        (escrowBalanceBefore - amount).toString(),
        "Escrow balance should decrease by unwrap amount"
      );
      assert.equal(
        recipientBalanceAfter.toString(),
        (recipientBalanceBefore + amount).toString(),
        "Recipient should receive unwrapped tokens"
      );
    });
  });
});

// Helper to create wrap message hash (matches WrapMessage in state.rs)
// Layout: forwarder_id(32) + token_mint(32) + amount(8) + nonce(8) + deadline(8) + action_tree_root(32) = 120 bytes
function createWrapMessageHash(
  forwarderId: PublicKey,
  tokenMint: PublicKey,
  amount: bigint,
  nonce: bigint,
  deadline: bigint,
  actionTreeRoot: Buffer
): Buffer {
  const { createHash } = require("crypto");
  const message = Buffer.alloc(120);
  forwarderId.toBuffer().copy(message, 0);   // forwarder_id for domain separation
  tokenMint.toBuffer().copy(message, 32);
  message.writeBigUInt64LE(amount, 64);
  message.writeBigUInt64LE(nonce, 72);
  message.writeBigInt64LE(deadline, 80);
  actionTreeRoot.copy(message, 88);
  return createHash("sha256").update(message).digest();
}
