import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  PublicKey,
  SystemProgram,
  Keypair,
  LAMPORTS_PER_SOL,
  ComputeBudgetProgram,
  SYSVAR_CLOCK_PUBKEY,
} from "@solana/web3.js";
import { assert } from "chai";
import { readFileSync } from "fs";
import path from "path";
import { SolanaPaPrototype } from "../target/types/solana_pa_prototype";

// Import helpers for PDA derivation (local utilities)
import {
  getRouterPda,
  getVerifierEntryPda,
  VERIFIER_ROUTER_ID,
  GROTH16_VERIFIER_ID,
} from "../scripts/verifier-utils";

type Fixture = {
  format: string;
  aggregation_strategy: string;
  aggregation_proof_type: string;
  selector: string; // "0x73c457ba" format
  tx_b64: string;
  tx_tampered_b64: string;
  consumed_nullifiers_b64: string[];
};

function readJson<T>(filePath: string): T {
  return JSON.parse(readFileSync(filePath, "utf8")) as T;
}

async function airdrop(provider: anchor.AnchorProvider, to: PublicKey, sol: number) {
  const sig = await provider.connection.requestAirdrop(to, sol * LAMPORTS_PER_SOL);
  await provider.connection.confirmTransaction(sig, "confirmed");
}

// PADDING_LEAF = ZEROS[0] from merkle.rs
const PADDING_LEAF = Buffer.from(
  "cc1d2f838445db7aec431df9ee8a871f40e7aa5e064fc056633ef8c60fab7b06",
  "hex"
);

// Empty tree root for depth-1 tree = ZEROS[0] = PADDING_LEAF
const EMPTY_TREE_ROOT_INITIAL = PADDING_LEAF;

// PDA seed constants (shared across all describe blocks)
const PA_STATE_SEED = Buffer.from("pa_state");
const NULLIFIER_SEED = Buffer.from("nullifier");
const TX_DATA_SEED = Buffer.from("tx_data");
const ROOT_SEED = Buffer.from("root");

// IDL path (shared across all IDL-inspection tests)
const IDL_PATH = path.resolve(process.cwd(), "target", "idl", "solana_pa_prototype.json");

// Parse selector from fixture (e.g., "0x73c457ba" -> Buffer)
function parseSelectorFromFixture(selectorHex: string): Buffer {
  const hex = selectorHex.replace(/^0x/, "");
  if (hex.length !== 8) {
    throw new Error(`Invalid selector format: ${selectorHex} (expected 8 hex chars)`);
  }
  return Buffer.from(hex, "hex");
}

// Generate a fresh upload ID and its little-endian encoding for TxData PDA derivation
function freshUploadId(): { uploadId: anchor.BN; uploadIdLe: Buffer } {
  const uploadId = new anchor.BN(Date.now());
  const uploadIdLe = Buffer.alloc(8);
  uploadIdLe.writeBigUInt64LE(BigInt(uploadId.toString()));
  return { uploadId, uploadIdLe };
}

// Extract error message + logs from an Anchor error for assertion matching
function errorHaystack(e: any): string {
  const msg = e?.error?.errorMessage ?? e?.toString?.() ?? "";
  const logs: string[] = e?.logs ?? e?.error?.logs ?? [];
  return [msg, ...logs].join("\n");
}

// Poll getSlot() until slot exceeds target. Used by TxData expiration tests.
async function waitForSlotPast(
  connection: anchor.web3.Connection,
  targetSlot: number,
  timeoutMs: number = 30000
): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const slot = await connection.getSlot("confirmed");
    if (slot > targetSlot) return;
    await new Promise((r) => setTimeout(r, 400));
  }
  throw new Error(`Timed out waiting for slot past ${targetSlot} after ${timeoutMs}ms`);
}

describe("solana-pa-prototype (Groth16 batch aggregation E2E)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const fixturePath = path.resolve(process.cwd(), "tests", "fixtures", "batch_groth16.json");
  const fixture = readJson<Fixture>(fixturePath);

  // Use devnet program IDs (downloaded from devnet and deployed to localnet)
  const groth16VerifierId = GROTH16_VERIFIER_ID;
  const verifierRouterId = VERIFIER_ROUTER_ID;

  const tx = Buffer.from(fixture.tx_b64, "base64");
  const txTampered = Buffer.from(fixture.tx_tampered_b64, "base64");

  // Read selector from fixture metadata (generated by fixture-gen)
  const GROTH16_SELECTOR = parseSelectorFromFixture(fixture.selector);

  // Router and verifier entry PDAs - derived using risc0-solana helpers
  let routerPda: PublicKey;
  let verifierEntryPda: PublicKey;

  // Helper to derive root PDA
  function deriveRootPda(root: Buffer): PublicKey {
    return PublicKey.findProgramAddressSync(
      [ROOT_SEED, paState.toBuffer(), root],
      program.programId
    )[0];
  }

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);
  const nullifierPdas = fixture.consumed_nullifiers_b64.map((nfB64) => {
    const nf = Buffer.from(nfB64, "base64");
    return PublicKey.findProgramAddressSync([NULLIFIER_SEED, paState.toBuffer(), nf], program.programId)[0];
  });

  const remainingAccounts = nullifierPdas.map((pubkey) => ({
    pubkey,
    isWritable: true,
    isSigner: false,
  }));

  // Must match `programs/block-time-forwarder/src/lib.rs::declare_id!`.
  const blockTimeForwarderId = new PublicKey("J1YYaBphwHzvGDq6EGY71DfPkuKWxMtHrtzGMUHp1LZ6");

  // Helper to settle with optional overrides for nullifier accounts and root markers
  async function settleViaTxData(
    authority: Keypair,
    payload: Buffer,
    options?: {
      nullifierAccounts?: { pubkey: PublicKey; isWritable: boolean; isSigner: boolean }[];
      newRootMarkerPda?: PublicKey;
      additionalHistoricalRootMarkers?: PublicKey[];
    }
  ) {
    await airdrop(provider, authority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    await program.methods
      .txdataInit(uploadId, payload.length, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    const chunkSize = 700;
    for (let offset = 0; offset < payload.length; offset += chunkSize) {
      const chunk = payload.subarray(offset, Math.min(payload.length, offset + chunkSize));
      await program.methods
        .txdataWrite(uploadId, offset, chunk)
        .accounts({
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
    }

    // Build remaining accounts:
    // [nullifier PDAs..., external call accounts..., historical root markers..., new root marker PDA]
    const allRemainingAccounts = [
      ...(options?.nullifierAccounts ?? remainingAccounts),
      { pubkey: blockTimeForwarderId, isWritable: false, isSigner: false },
      { pubkey: SYSVAR_CLOCK_PUBKEY, isWritable: false, isSigner: false },
    ];

    if (options?.additionalHistoricalRootMarkers) {
      for (const marker of options.additionalHistoricalRootMarkers) {
        allRemainingAccounts.push({ pubkey: marker, isWritable: false, isSigner: false });
      }
    }

    if (options?.newRootMarkerPda) {
      allRemainingAccounts.push({
        pubkey: options.newRootMarkerPda,
        isWritable: true,
        isSigner: false,
      });
    }

    return program.methods
      .settleFromTxdata(uploadId)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
        verifierRouterProgram: verifierRouterId,
        router: routerPda,
        verifierEntry: verifierEntryPda,
        verifierProgram: groth16VerifierId,
      })
      .remainingAccounts(allRemainingAccounts)
      .preInstructions([
        ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
        ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
      ])
      .signers([authority])
      .rpc();
  }

  // Track the genesis root marker PDA for testing
  let genesisRootMarkerPda: PublicKey;

  before(async () => {
    [routerPda] = getRouterPda(verifierRouterId);
    [verifierEntryPda] = getVerifierEntryPda(GROTH16_SELECTOR, verifierRouterId);

    genesisRootMarkerPda = deriveRootPda(EMPTY_TREE_ROOT_INITIAL);

    try {
      await program.account.paStateAccount.fetch(paState);
    } catch {
      // Initialize with genesis root marker in remaining_accounts
      await program.methods
        .initialize()
        .accounts({
          paState,
          payer: provider.wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .remainingAccounts([
          { pubkey: genesisRootMarkerPda, isWritable: true, isSigner: false },
        ])
        .rpc();
    }
  });

  // ==========================================================================
  // Issue #4: Historical Root Marker Tests
  // ==========================================================================

  it("creates genesis root marker on initialize", async () => {
    // The genesis root marker should have been created during before() hook
    const info = await provider.connection.getAccountInfo(genesisRootMarkerPda);
    assert.ok(info, "Genesis root marker PDA should exist after initialize");
    assert.ok(
      info!.owner.equals(program.programId),
      "Genesis root marker should be owned by PA program"
    );
    // Root markers are 0-byte accounts (existence = membership)
    assert.equal(info!.data.length, 0, "Root marker should be 0 bytes (existence-only)");
  });

  // ==========================================================================
  // Variable-Depth Merkle Tree Tests
  // ==========================================================================

  it("initializes with depth 1 (variable-depth tree)", async () => {
    const state = await program.account.paStateAccount.fetch(paState);
    assert.equal(
      state.currentDepth,
      1,
      "Initial tree depth should be 1 (capacity = 2 leaves)"
    );
    // Frontier is a Vec with length = currentDepth
    assert.equal(
      state.frontier.length,
      1,
      "Initial frontier should have 1 element (depth 1)"
    );
    // Initial root should be ZEROS[0] = PADDING_LEAF
    const rootBytes = Buffer.from(state.root as number[]);
    assert.deepEqual(
      rootBytes,
      EMPTY_TREE_ROOT_INITIAL,
      "Initial root should be ZEROS[0] for depth-1 tree"
    );
  });

  it("account size matches expected size for current depth (no over-allocation)", async () => {
    // Space formula: BASE_SPACE (99) + VEC_OVERHEAD (4) + 32 * depth
    const BASE_SPACE = 99;
    const VEC_OVERHEAD = 4;
    const spaceForDepth = (depth: number) => BASE_SPACE + VEC_OVERHEAD + 32 * depth;

    const state = await program.account.paStateAccount.fetch(paState);
    const accountInfo = await provider.connection.getAccountInfo(paState);

    assert.ok(accountInfo, "PAState account should exist");

    const expectedSize = spaceForDepth(state.currentDepth);
    assert.equal(
      accountInfo!.data.length,
      expectedSize,
      `Account size (${accountInfo!.data.length}) should match expected size for depth ${state.currentDepth} (${expectedSize})`
    );
  });

  it("rejects Delta::Witness (balance conservation bypass attempt)", async () => {
    // Clone the valid tx bytes and patch Delta::Proof to Delta::Witness
    const txWitness = Buffer.from(tx);

    // In bincode, Delta enum is serialized as:
    // - u32 variant index (0 = Witness, 1 = Proof)
    // - u64 length prefix (DeltaProof uses serialize_bytes → 65 = 0x41)
    // - payload bytes (DeltaProof = 65 bytes)
    //
    // Patching variant from 1 (Proof) to 0 (Witness) causes the deserializer
    // to misinterpret subsequent bytes, shifting all fields. This will either
    // produce an ExpectedDeltaProof error or an Invalid transaction data error.
    // Search for the unique 12-byte pattern: variant(1) + length(65) to avoid
    // matching other [01 00 00 00] occurrences (e.g. Vec length at offset 0).
    const deltaProofHeader = Buffer.from([
      0x01, 0x00, 0x00, 0x00, // variant index 1 (Proof)
      0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // length prefix 65
    ]);

    const idx = txWitness.indexOf(deltaProofHeader);
    if (idx === -1) {
      throw new Error("Could not find Delta::Proof variant+length tag in tx bytes");
    }

    // Patch variant from 1 (Proof) to 0 (Witness)
    txWitness.writeUInt32LE(0, idx);

    try {
      await settleViaTxData(Keypair.generate(), txWitness);
      assert.fail("expected settle to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(haystack, /ExpectedDeltaProof|Expected delta proof|Invalid transaction data/i);
    }
  });

  it("rejects a tampered tx (proof binding)", async () => {
    try {
      await settleViaTxData(Keypair.generate(), txTampered);
      assert.fail("expected settle to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(haystack, /Proof verification failed|ProofVerificationFailed|Verification error/);
    }
  });

  it("accepts a valid Groth16 batch aggregation tx and creates root marker", async () => {
    // Guardrail: fixture should actually include a block-time-forwarder external call.
    // If not present, this test can pass without exercising the external call path.
    assert.ok(
      tx.includes(Buffer.from(blockTimeForwarderId.toBytes())),
      "fixture tx must include block-time-forwarder program id bytes (external_payload injected)"
    );

    // Get the current state before settlement to know the pre-settlement root
    const stateBefore = await program.account.paStateAccount.fetch(paState);
    const rootBeforeBytes = Buffer.from(stateBefore.root as number[]);

    // We need to predict the new root after settlement to create the marker PDA
    // For now, we'll settle first without the marker, then verify the new root
    // In production, the client would compute this off-chain

    await settleViaTxData(Keypair.generate(), tx);

    // Verify nullifier PDAs exist
    for (const pda of nullifierPdas) {
      const info = await provider.connection.getAccountInfo(pda);
      assert.ok(info, "nullifier marker PDA should exist");
      assert.ok(info!.owner.equals(program.programId), "nullifier marker PDA should be owned by PA program");
    }

    const stateAfter = await program.account.paStateAccount.fetch(paState);
    assert.equal(stateAfter.nextIndex.toNumber(), 1);

    // Verify the root changed after settlement
    const rootAfterBytes = Buffer.from(stateAfter.root as number[]);
    assert.notDeepEqual(
      rootAfterBytes,
      rootBeforeBytes,
      "Root should change after appending commitment"
    );
  });

  // ==========================================================================
  // External Call Output Mismatch Test
  // Mirrors EVM PA: testFuzz_execute_reverts_on_unexpected_forwarder_call_output
  // ==========================================================================

  it("reverts on unexpected forwarder call output (ExternalCallOutputMismatch)", async () => {
    // This test uses a fixture where:
    // - timestamp = -1 (past time, forwarder will return RESULT_LT = 0x00)
    // - expected_output = 0x02 (RESULT_GT - intentionally WRONG)
    // The PA should revert with ExternalCallOutputMismatch when actual != expected.
    const mismatchFixturePath = path.resolve(
      process.cwd(), "tests", "fixtures", "batch_groth16_mismatch.json"
    );

    const mismatchFixture = readJson<Fixture>(mismatchFixturePath);
    const mismatchTx = Buffer.from(mismatchFixture.tx_b64, "base64");

    const mismatchNullifierAccounts = mismatchFixture.consumed_nullifiers_b64.map((nfB64) => {
      const nf = Buffer.from(nfB64, "base64");
      const pubkey = PublicKey.findProgramAddressSync([NULLIFIER_SEED, paState.toBuffer(), nf], program.programId)[0];
      return { pubkey, isWritable: true, isSigner: false };
    });

    try {
      await settleViaTxData(Keypair.generate(), mismatchTx, {
        nullifierAccounts: mismatchNullifierAccounts,
      });
      assert.fail("expected settle to fail with ExternalCallOutputMismatch");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /ExternalCallOutputMismatch|external call output mismatch/i,
        "Should fail with ExternalCallOutputMismatch error"
      );
    }
  });
});

// =============================================================================
// Re-initialization guard
// =============================================================================

describe("solana-pa-prototype (Re-initialization guard)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);

  it("rejects re-initialization of PAState", async () => {
    // PAState was already initialized in the E2E before() hook.
    // A second initialize call must fail because the account already exists.
    const genesisRootMarkerPda = PublicKey.findProgramAddressSync(
      [ROOT_SEED, paState.toBuffer(), EMPTY_TREE_ROOT_INITIAL],
      program.programId
    )[0];

    try {
      await program.methods
        .initialize()
        .accounts({
          paState,
          payer: provider.wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .remainingAccounts([
          { pubkey: genesisRootMarkerPda, isWritable: true, isSigner: false },
        ])
        .rpc();
      assert.fail("expected re-initialization to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      // Anchor's init constraint rejects when the account already exists
      assert.match(
        haystack,
        /already in use|already been initialized|0x0/i,
        `Expected 'already in use' error, got: ${haystack}`
      );
    }
  });
});

// =============================================================================
// Direct settle instruction and duplicate nullifier
// =============================================================================

describe("solana-pa-prototype (Direct settle & duplicate nullifier)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);

  const fixturePath = path.resolve(process.cwd(), "tests", "fixtures", "batch_groth16.json");
  const fixture = readJson<Fixture>(fixturePath);

  const groth16VerifierId = GROTH16_VERIFIER_ID;
  const verifierRouterId = VERIFIER_ROUTER_ID;
  const GROTH16_SELECTOR = parseSelectorFromFixture(fixture.selector);

  let routerPda: PublicKey;
  let verifierEntryPda: PublicKey;

  const blockTimeForwarderId = new PublicKey("J1YYaBphwHzvGDq6EGY71DfPkuKWxMtHrtzGMUHp1LZ6");

  before(async () => {
    [routerPda] = getRouterPda(verifierRouterId);
    [verifierEntryPda] = getVerifierEntryPda(GROTH16_SELECTOR, verifierRouterId);
  });

  it("rejects garbage transaction_data via settle", async () => {
    const payer = Keypair.generate();
    await airdrop(provider, payer.publicKey, 2);

    try {
      await program.methods
        .settle(Buffer.from([0, 1, 2, 3]))
        .accounts({
          paState,
          payer: payer.publicKey,
          systemProgram: SystemProgram.programId,
          verifierRouterProgram: verifierRouterId,
          router: routerPda,
          verifierEntry: verifierEntryPda,
          verifierProgram: groth16VerifierId,
        })
        .preInstructions([
          ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
          ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        ])
        .signers([payer])
        .rpc();
      assert.fail("expected settle with garbage data to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /InvalidTransactionData|Invalid transaction data/i,
        `Expected InvalidTransactionData, got: ${haystack}`
      );
    }
  });

  it("rejects duplicate nullifier (double-spend) via settle_from_txdata", async () => {
    // T-06 already consumed the fixture's nullifiers. Re-uploading the same tx
    // to a fresh TxData and trying to settle must fail at nullifier creation
    // because those nullifier PDAs already exist.
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const tx = Buffer.from(fixture.tx_b64, "base64");
    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    // Init TxData
    await program.methods
      .txdataInit(uploadId, tx.length, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Write payload in chunks
    const chunkSize = 700;
    for (let offset = 0; offset < tx.length; offset += chunkSize) {
      const chunk = tx.subarray(offset, Math.min(tx.length, offset + chunkSize));
      await program.methods
        .txdataWrite(uploadId, offset, chunk)
        .accounts({
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
    }

    // Build remaining accounts with the SAME nullifier PDAs (already created by T-06)
    const nullifierPdas = fixture.consumed_nullifiers_b64.map((nfB64) => {
      const nf = Buffer.from(nfB64, "base64");
      return PublicKey.findProgramAddressSync(
        [NULLIFIER_SEED, paState.toBuffer(), nf],
        program.programId
      )[0];
    });

    const nullifierAccounts = nullifierPdas.map((pubkey) => ({
      pubkey,
      isWritable: true,
      isSigner: false,
    }));

    const allRemainingAccounts = [
      ...nullifierAccounts,
      { pubkey: blockTimeForwarderId, isWritable: false, isSigner: false },
      { pubkey: SYSVAR_CLOCK_PUBKEY, isWritable: false, isSigner: false },
    ];

    try {
      await program.methods
        .settleFromTxdata(uploadId)
        .accounts({
          paState,
          txData,
          authority: authority.publicKey,
          systemProgram: SystemProgram.programId,
          verifierRouterProgram: verifierRouterId,
          router: routerPda,
          verifierEntry: verifierEntryPda,
          verifierProgram: groth16VerifierId,
        })
        .remainingAccounts(allRemainingAccounts)
        .preInstructions([
          ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
          ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        ])
        .signers([authority])
        .rpc();
      assert.fail("expected duplicate nullifier to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /DuplicateNullifier|duplicate nullifier|already in use/i,
        `Expected DuplicateNullifier, got: ${haystack}`
      );
    }
  });
});

// =============================================================================
// Settle error paths
// =============================================================================

describe("solana-pa-prototype (Settle error paths)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);

  const fixturePath = path.resolve(process.cwd(), "tests", "fixtures", "batch_groth16.json");
  const fixture = readJson<Fixture>(fixturePath);

  const groth16VerifierId = GROTH16_VERIFIER_ID;
  const verifierRouterId = VERIFIER_ROUTER_ID;
  const GROTH16_SELECTOR = parseSelectorFromFixture(fixture.selector);

  let routerPda: PublicKey;
  let verifierEntryPda: PublicKey;

  before(async () => {
    [routerPda] = getRouterPda(verifierRouterId);
    [verifierEntryPda] = getVerifierEntryPda(GROTH16_SELECTOR, verifierRouterId);
  });

  it("rejects wrong verifier_router_program address", async () => {
    const payer = Keypair.generate();
    await airdrop(provider, payer.publicKey, 2);

    const fakeRouter = Keypair.generate().publicKey;

    try {
      await program.methods
        .settle(Buffer.from([0, 1, 2, 3]))
        .accounts({
          paState,
          payer: payer.publicKey,
          systemProgram: SystemProgram.programId,
          verifierRouterProgram: fakeRouter,
          router: routerPda,
          verifierEntry: verifierEntryPda,
          verifierProgram: groth16VerifierId,
        })
        .preInstructions([
          ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
        ])
        .signers([payer])
        .rpc();
      assert.fail("expected wrong verifier_router_program to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /ConstraintAddress|address constraint/i,
        `Expected ConstraintAddress, got: ${haystack}`
      );
    }
  });

  it("rejects insufficient remaining_accounts for nullifiers", async () => {
    // Upload the fixture but pass zero nullifier accounts.
    // The program expects 1 nullifier PDA in remaining_accounts.
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const mismatchFixturePath = path.resolve(
      process.cwd(), "tests", "fixtures", "batch_groth16_mismatch.json"
    );
    const mismatchFixture = readJson<Fixture>(mismatchFixturePath);
    const mismatchTx = Buffer.from(mismatchFixture.tx_b64, "base64");

    const { uploadId, uploadIdLe } = freshUploadId();
    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    await program.methods
      .txdataInit(uploadId, mismatchTx.length, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    const chunkSize = 700;
    for (let offset = 0; offset < mismatchTx.length; offset += chunkSize) {
      const chunk = mismatchTx.subarray(offset, Math.min(mismatchTx.length, offset + chunkSize));
      await program.methods
        .txdataWrite(uploadId, offset, chunk)
        .accounts({
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
    }

    const blockTimeForwarderId = new PublicKey("J1YYaBphwHzvGDq6EGY71DfPkuKWxMtHrtzGMUHp1LZ6");

    // Pass ZERO nullifier accounts but still include forwarder+clock
    const allRemainingAccounts = [
      { pubkey: blockTimeForwarderId, isWritable: false, isSigner: false },
      { pubkey: SYSVAR_CLOCK_PUBKEY, isWritable: false, isSigner: false },
    ];

    try {
      await program.methods
        .settleFromTxdata(uploadId)
        .accounts({
          paState,
          txData,
          authority: authority.publicKey,
          systemProgram: SystemProgram.programId,
          verifierRouterProgram: verifierRouterId,
          router: routerPda,
          verifierEntry: verifierEntryPda,
          verifierProgram: groth16VerifierId,
        })
        .remainingAccounts(allRemainingAccounts)
        .preInstructions([
          ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
          ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        ])
        .signers([authority])
        .rpc();
      assert.fail("expected insufficient remaining_accounts to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      // With zero nullifier accounts, the program consumes what would be
      // the forwarder/clock slots as nullifier PDAs, then can't find the
      // forwarder in the remaining accounts. This manifests as
      // UnregisteredForwarder or NullifierPdaMismatch.
      assert.match(
        haystack,
        /NullifierPdaMismatch|UnregisteredForwarder|InvalidTransactionData|index out of bounds|panicked/i,
        `Expected remaining_accounts error, got: ${haystack}`
      );
    }
  });
});

// =============================================================================
// Issue #6: Emergency Stop / Pausable Tests
// =============================================================================
// These tests verify the one-way emergency stop mechanism (EVM parity).
// Once paused, recovery requires a program upgrade.

describe("solana-pa-prototype (Issue #6: Emergency Stop)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);

  it("stores authority on PAStateAccount after initialize", async () => {
    const state = await program.account.paStateAccount.fetch(paState);
    assert.ok(state.authority, "State should have authority field");
    // Authority should be a valid pubkey (not all zeros)
    const authorityBytes = state.authority.toBytes();
    const isZero = authorityBytes.every((b: number) => b === 0);
    assert.ok(!isZero, "Authority should not be all zeros");
  });

  it("initializes with paused=false", async () => {
    const state = await program.account.paStateAccount.fetch(paState);
    assert.equal(state.paused, false, "State should be unpaused after initialize");
  });

  it("rejects emergency_stop from non-authority", async () => {
    const nonAuthority = Keypair.generate();
    await airdrop(provider, nonAuthority.publicKey, 1);

    try {
      await program.methods
        .emergencyStop()
        .accounts({
          paState,
          authority: nonAuthority.publicKey,
        })
        .signers([nonAuthority])
        .rpc();
      assert.fail("expected emergency_stop to fail for non-authority");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      // Anchor's has_one constraint produces "A has one constraint was violated"
      // or our custom error "Unauthorized"
      assert.match(
        haystack,
        /Unauthorized|has.?one.*constraint.*violated|ConstraintHasOne/i,
        "Should fail with Unauthorized or has_one constraint error"
      );
    }
  });

  it("rejects transfer_authority from non-authority", async () => {
    const nonAuthority = Keypair.generate();
    const newAuthority = Keypair.generate();
    await airdrop(provider, nonAuthority.publicKey, 1);

    try {
      await program.methods
        .transferAuthority(newAuthority.publicKey)
        .accounts({
          paState,
          authority: nonAuthority.publicKey,
        })
        .signers([nonAuthority])
        .rpc();
      assert.fail("expected transfer_authority to fail for non-authority");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /Unauthorized|has.?one.*constraint.*violated|ConstraintHasOne/i,
        "Should fail with Unauthorized or has_one constraint error"
      );
    }
  });

  it("transfers authority when called by current authority", async () => {
    // Get current authority from state
    const stateBefore = await program.account.paStateAccount.fetch(paState);
    const currentAuthority = stateBefore.authority;

    // Create new authority
    const newAuthority = Keypair.generate();
    await airdrop(provider, newAuthority.publicKey, 1);

    // Transfer authority using provider wallet (which should be the current authority)
    await program.methods
      .transferAuthority(newAuthority.publicKey)
      .accounts({
        paState,
        authority: provider.wallet.publicKey,
      })
      .rpc();

    // Verify authority was updated
    const stateAfter = await program.account.paStateAccount.fetch(paState);
    assert.ok(
      stateAfter.authority.equals(newAuthority.publicKey),
      "Authority should be updated to new authority"
    );

    // Transfer back to original authority for other tests
    await program.methods
      .transferAuthority(currentAuthority)
      .accounts({
        paState,
        authority: newAuthority.publicKey,
      })
      .signers([newAuthority])
      .rpc();

    // Verify authority was restored
    const stateRestored = await program.account.paStateAccount.fetch(paState);
    assert.ok(
      stateRestored.authority.equals(currentAuthority),
      "Authority should be restored to original"
    );
  });

  it("old authority cannot call emergency_stop after transfer", async () => {
    const stateBefore = await program.account.paStateAccount.fetch(paState);
    const originalAuthority = stateBefore.authority;

    // Create new authority
    const newAuthority = Keypair.generate();
    await airdrop(provider, newAuthority.publicKey, 1);

    // Transfer authority
    await program.methods
      .transferAuthority(newAuthority.publicKey)
      .accounts({
        paState,
        authority: provider.wallet.publicKey,
      })
      .rpc();

    // Old authority should not be able to call emergency_stop
    try {
      await program.methods
        .emergencyStop()
        .accounts({
          paState,
          authority: provider.wallet.publicKey,
        })
        .rpc();
      assert.fail("expected emergency_stop to fail for old authority");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /Unauthorized|has.?one.*constraint.*violated|ConstraintHasOne/i,
        "Should fail with Unauthorized or has_one constraint error"
      );
    }

    // Restore original authority
    await program.methods
      .transferAuthority(originalAuthority)
      .accounts({
        paState,
        authority: newAuthority.publicKey,
      })
      .signers([newAuthority])
      .rpc();
  });

  // NOTE: The following tests are destructive - they pause the protocol.
  // We use a separate describe block with its own PAState to avoid affecting other tests.
});

describe("solana-pa-prototype (Issue #6: Emergency Stop - Destructive)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  // We can't easily create a second PAState without modifying the program seeds.
  // Instead, we'll test the emergency_stop behavior conceptually by:
  // 1. Skipping the actual pause test (would break other tests)
  // 2. Verifying the error messages are correct

  it("verifies emergency_stop instruction exists in IDL", async () => {
    // Read IDL directly from file (more reliable than program.idl)
    const idl = readJson<any>(IDL_PATH);
    // IDL uses snake_case: emergency_stop
    const emergencyStopIx = idl.instructions.find((ix: any) => ix.name === "emergency_stop");
    assert.ok(emergencyStopIx, "emergency_stop instruction should exist in IDL");
  });

  it("verifies transfer_authority instruction exists in IDL", async () => {
    const idl = readJson<any>(IDL_PATH);
    const transferAuthorityIx = idl.instructions.find((ix: any) => ix.name === "transfer_authority");
    assert.ok(transferAuthorityIx, "transfer_authority instruction should exist in IDL");
    // Verify it has the new_authority argument
    const newAuthorityArg = transferAuthorityIx.args?.find((arg: any) => arg.name === "new_authority" || arg.name === "newAuthority");
    assert.ok(newAuthorityArg, "transfer_authority should have new_authority argument");
  });

  it("verifies paused check exists in settle instructions", async () => {
    // Read IDL directly from file
    const idl = readJson<any>(IDL_PATH);
    const pausedError = idl.errors?.find((e: any) => e.name === "Paused");
    assert.ok(pausedError, "Paused error should exist in IDL");
    assert.match(pausedError.msg, /paused/i, "Error message should mention paused");
  });

  it("verifies AlreadyPaused error exists", async () => {
    const idl = readJson<any>(IDL_PATH);
    const alreadyPausedError = idl.errors?.find((e: any) => e.name === "AlreadyPaused");
    assert.ok(alreadyPausedError, "AlreadyPaused error should exist in IDL");
  });

  it("verifies Unauthorized error exists", async () => {
    const idl = readJson<any>(IDL_PATH);
    const unauthorizedError = idl.errors?.find((e: any) => e.name === "Unauthorized");
    assert.ok(unauthorizedError, "Unauthorized error should exist in IDL");
  });
});

// =============================================================================
// TxData Expiration Mechanism Tests
// =============================================================================

describe("solana-pa-prototype (TxData Expiration)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);

  // Constants matching Rust (from state.rs)
  const MIN_EXPIRY_SLOTS = 100;
  const MAX_EXPIRY_SLOTS = 216_000;

  it("rejects txdata_init with expires_slot too soon", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 1);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    // Set expiry too soon (only 50 slots from now, MIN is 100)
    const expiresSlot = new anchor.BN(slot + 50);

    try {
      await program.methods
        .txdataInit(uploadId, 100, expiresSlot)
        .accounts({
          paState,
          txData,
          authority: authority.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([authority])
        .rpc();
      assert.fail("expected txdata_init to fail with TxDataExpiryTooSoon");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(haystack, /TxDataExpiryTooSoon|expires_slot is below minimum/i);
    }
  });

  it("rejects txdata_init with expires_slot too late", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 1);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    // Set expiry too late (MAX + 1000 slots from now)
    const expiresSlot = new anchor.BN(slot + MAX_EXPIRY_SLOTS + 1000);

    try {
      await program.methods
        .txdataInit(uploadId, 100, expiresSlot)
        .accounts({
          paState,
          txData,
          authority: authority.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([authority])
        .rpc();
      assert.fail("expected txdata_init to fail with TxDataExpiryTooLate");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(haystack, /TxDataExpiryTooLate|expires_slot exceeds maximum/i);
    }
  });

  it("accepts txdata_init with valid expires_slot", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 1);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    // Set expiry at midpoint of valid range
    const expiresSlot = new anchor.BN(slot + Math.floor((MIN_EXPIRY_SLOTS + MAX_EXPIRY_SLOTS) / 2));

    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    const txDataAccount = await program.account.txDataAccount.fetch(txData);
    assert.equal(
      txDataAccount.expiresSlot.toNumber(),
      expiresSlot.toNumber(),
      "expires_slot should be set correctly"
    );
  });

  it("allows authority to close TxData anytime", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    // Create TxData
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Verify it exists
    const before = await provider.connection.getAccountInfo(txData);
    assert.ok(before, "TxData should exist before close");

    // Get balance before close
    const balanceBefore = await provider.connection.getBalance(authority.publicKey);

    // Close TxData (authority receives rent back)
    await program.methods
      .txdataClose(uploadId)
      .accounts({
        txData,
        authority: authority.publicKey,
        refund: authority.publicKey,
      })
      .signers([authority])
      .rpc();

    // Verify it's closed
    const after = await provider.connection.getAccountInfo(txData);
    assert.ok(!after, "TxData should not exist after close");

    // Verify rent was refunded
    const balanceAfter = await provider.connection.getBalance(authority.publicKey);
    assert.ok(
      balanceAfter > balanceBefore,
      "Authority balance should increase after close (rent refund)"
    );
  });

  // -------------------------------------------------------------------------
  // Security tests for txdata_close authorization
  // -------------------------------------------------------------------------
  // These tests document the two-layer security model:
  // 1. PDA derivation includes authority's pubkey in seeds - attacker derives different PDA
  // 2. Anchor's seeds constraint verifies PDA matches signer - can't pass someone else's PDA
  // -------------------------------------------------------------------------

  it("rejects txdata_close for non-existent account (attacker's PDA doesn't exist)", async () => {
    // SCENARIO: Attacker derives their OWN PDA (using their pubkey in seeds).
    // Since they never created a TxData at that address, it doesn't exist.
    // This tests Anchor's account existence check.
    const authority = Keypair.generate();
    const attacker = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);
    await airdrop(provider, attacker.publicKey, 1);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [authorityTxData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    // Authority creates TxData at their PDA
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData: authorityTxData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Attacker derives THEIR OWN PDA (different address because attacker.pubkey != authority.pubkey)
    const [attackerTxData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, attacker.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    // Attacker tries to close their own (non-existent) PDA
    try {
      await program.methods
        .txdataClose(uploadId)
        .accounts({
          txData: attackerTxData,
          authority: attacker.publicKey,
          refund: attacker.publicKey,
        })
        .signers([attacker])
        .rpc();
      assert.fail("should have failed - attackerTxData doesn't exist");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      // MUST be AccountNotInitialized - any other error indicates a different bug
      assert.match(
        haystack,
        /AccountNotInitialized/,
        `Expected AccountNotInitialized (account doesn't exist), got: ${haystack}`
      );
    }
  });

  it("rejects txdata_close when attacker passes authority's PDA directly (seed constraint)", async () => {
    // SCENARIO: Attacker KNOWS authority's TxData address and passes it directly.
    // But Anchor's seeds constraint computes [TX_DATA_SEED, signer.key(), upload_id].
    // Since signer is attacker, computed PDA != authority's PDA → ConstraintSeeds error.
    // This tests Anchor's PDA seed verification.
    const authority = Keypair.generate();
    const attacker = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);
    await airdrop(provider, attacker.publicKey, 1);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [authorityTxData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    // Authority creates TxData
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData: authorityTxData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Attacker tries to close AUTHORITY'S TxData by passing the address directly
    // Anchor will compute seeds with attacker.pubkey → different PDA → constraint fails
    try {
      await program.methods
        .txdataClose(uploadId)
        .accounts({
          txData: authorityTxData,  // <-- Attacker passes authority's actual TxData
          authority: attacker.publicKey,
          refund: attacker.publicKey,
        })
        .signers([attacker])
        .rpc();
      assert.fail("should have failed - seed constraint should reject");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      // MUST be ConstraintSeeds - Anchor computes PDA from signer, doesn't match passed account
      assert.match(
        haystack,
        /ConstraintSeeds|seeds constraint was violated/i,
        `Expected ConstraintSeeds (PDA mismatch), got: ${haystack}`
      );
    }
  });

  it("verifies new error types exist in IDL", async () => {
    const idl = readJson<any>(IDL_PATH);

    const expiryTooSoonError = idl.errors?.find((e: any) => e.name === "TxDataExpiryTooSoon");
    assert.ok(expiryTooSoonError, "TxDataExpiryTooSoon error should exist in IDL");

    const expiryTooLateError = idl.errors?.find((e: any) => e.name === "TxDataExpiryTooLate");
    assert.ok(expiryTooLateError, "TxDataExpiryTooLate error should exist in IDL");
  });

  // ===========================================================================
  // Tests for txdata_extend instruction
  // ===========================================================================

  it("verifies txdata_extend instruction exists in IDL", async () => {
    const idl = readJson<any>(IDL_PATH);
    const txdataExtendIx = idl.instructions.find((ix: any) => ix.name === "txdata_extend");
    assert.ok(txdataExtendIx, "txdata_extend instruction should exist in IDL");
    // Verify it has new_expires_slot argument
    const newExpiresArg = txdataExtendIx.args?.find((arg: any) => arg.name === "new_expires_slot" || arg.name === "newExpiresSlot");
    assert.ok(newExpiresArg, "txdata_extend should have new_expires_slot argument");
  });

  it("extends TxData expiration deadline successfully", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const initialExpiry = new anchor.BN(slot + 1000);

    // Create TxData
    await program.methods
      .txdataInit(uploadId, 100, initialExpiry)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Verify initial expiry
    let txDataAccount = await program.account.txDataAccount.fetch(txData);
    assert.equal(txDataAccount.expiresSlot.toNumber(), initialExpiry.toNumber());

    // Extend expiration
    const currentSlot = await provider.connection.getSlot("confirmed");
    const newExpiry = new anchor.BN(currentSlot + 5000);

    await program.methods
      .txdataExtend(uploadId, newExpiry)
      .accountsStrict({
        paState,
        txData,
        authority: authority.publicKey,
      })
      .signers([authority])
      .rpc();

    // Verify new expiry
    txDataAccount = await program.account.txDataAccount.fetch(txData);
    assert.equal(txDataAccount.expiresSlot.toNumber(), newExpiry.toNumber(), "expires_slot should be updated");
  });

  it("rejects txdata_extend that doesn't increase expires_slot", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const initialExpiry = new anchor.BN(slot + 10000);

    // Create TxData with high expiry
    await program.methods
      .txdataInit(uploadId, 100, initialExpiry)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Try to extend to a lower value (should fail)
    const currentSlot = await provider.connection.getSlot("confirmed");
    const lowerExpiry = new anchor.BN(currentSlot + 500); // Less than current expires_slot

    try {
      await program.methods
        .txdataExtend(uploadId, lowerExpiry)
        .accountsStrict({
          paState,
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
      assert.fail("expected txdata_extend to fail with TxDataExtendMustIncrease");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(haystack, /TxDataExtendMustIncrease|extension must increase/i);
    }
  });

  // ===========================================================================
  // Tests for txdata_close_expired instruction
  // ===========================================================================

  it("verifies txdata_close_expired instruction exists in IDL", async () => {
    const idl = readJson<any>(IDL_PATH);
    const txdataCloseExpiredIx = idl.instructions.find((ix: any) => ix.name === "txdata_close_expired");
    assert.ok(txdataCloseExpiredIx, "txdata_close_expired instruction should exist in IDL");
    // Verify it has authority argument (to derive PDA)
    const authorityArg = txdataCloseExpiredIx.args?.find((arg: any) => arg.name === "_authority");
    assert.ok(authorityArg, "txdata_close_expired should have _authority argument (used for PDA derivation)");
  });

  it("rejects txdata_close_expired for non-expired TxData", async () => {
    const authority = Keypair.generate();
    const cleaner = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);
    await airdrop(provider, cleaner.publicKey, 1);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 50000); // Far in the future

    // Create TxData
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Try to close_expired (should fail - not expired yet)
    try {
      await program.methods
        .txdataCloseExpired(uploadId, authority.publicKey)
        .accountsStrict({
          txData,
          payer: cleaner.publicKey,
          refund: authority.publicKey,
        })
        .signers([cleaner])
        .rpc();
      assert.fail("expected txdata_close_expired to fail with TxDataNotExpired");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(haystack, /TxDataNotExpired|has not expired/i);
    }
  });

  // ===========================================================================
  // Tests for update_expiry_config instruction
  // ===========================================================================

  it("verifies update_expiry_config instruction exists in IDL", async () => {
    const idl = readJson<any>(IDL_PATH);
    const updateExpiryConfigIx = idl.instructions.find((ix: any) => ix.name === "update_expiry_config");
    assert.ok(updateExpiryConfigIx, "update_expiry_config instruction should exist in IDL");
    // Verify it has the two arguments (IDL uses snake_case)
    assert.equal(updateExpiryConfigIx.args?.length, 2, "update_expiry_config should have 2 arguments");
  });

  it("verifies new error types for expiry features exist in IDL", async () => {
    const idl = readJson<any>(IDL_PATH);

    const extendMustIncreaseError = idl.errors?.find((e: any) => e.name === "TxDataExtendMustIncrease");
    assert.ok(extendMustIncreaseError, "TxDataExtendMustIncrease error should exist in IDL");

    const notExpiredError = idl.errors?.find((e: any) => e.name === "TxDataNotExpired");
    assert.ok(notExpiredError, "TxDataNotExpired error should exist in IDL");

    const invalidConfigError = idl.errors?.find((e: any) => e.name === "InvalidExpiryConfig");
    assert.ok(invalidConfigError, "InvalidExpiryConfig error should exist in IDL");
  });
});

// =============================================================================
// TxData authority and bounds checks
// =============================================================================

describe("solana-pa-prototype (TxData authority and bounds checks)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);

  it("rejects txdata_write that exceeds payload capacity", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    // Init TxData with capacity=100
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Write 200 bytes at offset 0 (exceeds capacity of 100)
    try {
      await program.methods
        .txdataWrite(uploadId, 0, Buffer.alloc(200))
        .accounts({
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
      assert.fail("expected txdata_write to fail with TxDataBoundsExceeded");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /TxDataBoundsExceeded|exceeds payload/i,
        `Expected TxDataBoundsExceeded, got: ${haystack}`
      );
    }
  });

  it("rejects txdata_write from wrong authority", async () => {
    const authority = Keypair.generate();
    const wrongAuthority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);
    await airdrop(provider, wrongAuthority.publicKey, 1);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    // Init TxData as authority
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Try to write as wrongAuthority — seed derivation uses signer's key,
    // which produces a different PDA, causing ConstraintSeeds
    try {
      await program.methods
        .txdataWrite(uploadId, 0, Buffer.alloc(10))
        .accounts({
          txData,
          authority: wrongAuthority.publicKey,
        })
        .signers([wrongAuthority])
        .rpc();
      assert.fail("expected txdata_write from wrong authority to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /ConstraintSeeds|ConstraintHasOne|has.?one|seeds constraint/i,
        `Expected authority constraint error, got: ${haystack}`
      );
    }
  });

  it("rejects settle_from_txdata from wrong authority", async () => {
    const authority = Keypair.generate();
    const wrongAuthority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);
    await airdrop(provider, wrongAuthority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    // Init and write as correct authority
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    await program.methods
      .txdataWrite(uploadId, 0, Buffer.alloc(50))
      .accounts({
        txData,
        authority: authority.publicKey,
      })
      .signers([authority])
      .rpc();

    // Try settle_from_txdata as wrongAuthority
    const GROTH16_SELECTOR = parseSelectorFromFixture(
      readJson<Fixture>(path.resolve(process.cwd(), "tests", "fixtures", "batch_groth16.json")).selector
    );
    const [routerPda] = getRouterPda(VERIFIER_ROUTER_ID);
    const [verifierEntryPda] = getVerifierEntryPda(GROTH16_SELECTOR, VERIFIER_ROUTER_ID);

    try {
      await program.methods
        .settleFromTxdata(uploadId)
        .accounts({
          paState,
          txData,
          authority: wrongAuthority.publicKey,
          systemProgram: SystemProgram.programId,
          verifierRouterProgram: VERIFIER_ROUTER_ID,
          router: routerPda,
          verifierEntry: verifierEntryPda,
          verifierProgram: GROTH16_VERIFIER_ID,
        })
        .preInstructions([
          ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
        ])
        .signers([wrongAuthority])
        .rpc();
      assert.fail("expected settle_from_txdata from wrong authority to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /ConstraintSeeds|ConstraintHasOne|has.?one|seeds constraint|Unauthorized/i,
        `Expected authority constraint error, got: ${haystack}`
      );
    }
  });

  it("rejects txdata_close with wrong refund address", async () => {
    const authority = Keypair.generate();
    const otherPubkey = Keypair.generate().publicKey;
    await airdrop(provider, authority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    // Init TxData (refund defaults to authority.publicKey)
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Close with wrong refund address
    try {
      await program.methods
        .txdataClose(uploadId)
        .accounts({
          txData,
          authority: authority.publicKey,
          refund: otherPubkey,
        })
        .signers([authority])
        .rpc();
      assert.fail("expected txdata_close with wrong refund to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /ConstraintAddress|address constraint/i,
        `Expected ConstraintAddress, got: ${haystack}`
      );
    }
  });

  it("rejects txdata_close_expired with wrong refund address", async () => {
    const authority = Keypair.generate();
    const cleaner = Keypair.generate();
    const wrongRefund = Keypair.generate().publicKey;
    await airdrop(provider, authority.publicKey, 2);
    await airdrop(provider, cleaner.publicKey, 1);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 50_000);

    // Init TxData
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Try close_expired with wrong refund — hits ConstraintAddress before TxDataNotExpired
    // because Anchor validates account constraints before running the handler body
    try {
      await program.methods
        .txdataCloseExpired(uploadId, authority.publicKey)
        .accountsStrict({
          txData,
          payer: cleaner.publicKey,
          refund: wrongRefund,
        })
        .signers([cleaner])
        .rpc();
      assert.fail("expected txdata_close_expired with wrong refund to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /ConstraintAddress|address constraint/i,
        `Expected ConstraintAddress, got: ${haystack}`
      );
    }
  });
});

// =============================================================================
// update_expiry_config tests
// =============================================================================

describe("solana-pa-prototype (update_expiry_config)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);

  const SEVEN_DAYS_SLOTS = 7 * 24 * 60 * 60 * 1000 / 400; // 1_512_000

  it("updates expiry config successfully", async () => {
    await program.methods
      .updateExpiryConfig(new anchor.BN(50), new anchor.BN(5000))
      .accounts({
        paState,
        authority: provider.wallet.publicKey,
      })
      .rpc();

    const state = await program.account.paStateAccount.fetch(paState);
    assert.equal(
      state.minExpirySlots.toNumber(),
      50,
      "min_expiry_slots should be 50"
    );
    assert.equal(
      state.maxExpirySlots.toNumber(),
      5000,
      "max_expiry_slots should be 5000"
    );
  });

  it("rejects min >= max", async () => {
    try {
      await program.methods
        .updateExpiryConfig(new anchor.BN(5000), new anchor.BN(100))
        .accounts({
          paState,
          authority: provider.wallet.publicKey,
        })
        .rpc();
      assert.fail("expected update_expiry_config with min >= max to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /InvalidExpiryConfig|Invalid expiry config/i,
        `Expected InvalidExpiryConfig, got: ${haystack}`
      );
    }
  });

  it("rejects min < 10", async () => {
    try {
      await program.methods
        .updateExpiryConfig(new anchor.BN(5), new anchor.BN(1000))
        .accounts({
          paState,
          authority: provider.wallet.publicKey,
        })
        .rpc();
      assert.fail("expected update_expiry_config with min < 10 to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /InvalidExpiryConfig|Invalid expiry config/i,
        `Expected InvalidExpiryConfig, got: ${haystack}`
      );
    }
  });

  it("rejects max > SEVEN_DAYS_SLOTS", async () => {
    try {
      await program.methods
        .updateExpiryConfig(new anchor.BN(50), new anchor.BN(SEVEN_DAYS_SLOTS + 1))
        .accounts({
          paState,
          authority: provider.wallet.publicKey,
        })
        .rpc();
      assert.fail("expected update_expiry_config with max > SEVEN_DAYS_SLOTS to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /InvalidExpiryConfig|Invalid expiry config/i,
        `Expected InvalidExpiryConfig, got: ${haystack}`
      );
    }
  });

  it("rejects wrong authority", async () => {
    const nonAuthority = Keypair.generate();
    await airdrop(provider, nonAuthority.publicKey, 1);

    try {
      await program.methods
        .updateExpiryConfig(new anchor.BN(50), new anchor.BN(5000))
        .accounts({
          paState,
          authority: nonAuthority.publicKey,
        })
        .signers([nonAuthority])
        .rpc();
      assert.fail("expected update_expiry_config from wrong authority to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /ConstraintHasOne|has.?one|Unauthorized/i,
        `Expected authority constraint error, got: ${haystack}`
      );
    }
  });

  it("restores default config", async () => {
    await program.methods
      .updateExpiryConfig(new anchor.BN(100), new anchor.BN(216_000))
      .accounts({
        paState,
        authority: provider.wallet.publicKey,
      })
      .rpc();

    const state = await program.account.paStateAccount.fetch(paState);
    assert.equal(state.minExpirySlots.toNumber(), 100, "min_expiry_slots should be restored to 100");
    assert.equal(state.maxExpirySlots.toNumber(), 216_000, "max_expiry_slots should be restored to 216_000");
  });
});

// =============================================================================
// TxData expiration enforcement
// =============================================================================

describe("solana-pa-prototype (TxData expiration enforcement)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);

  const fixturePath = path.resolve(process.cwd(), "tests", "fixtures", "batch_groth16.json");
  const fixture = readJson<Fixture>(fixturePath);

  const groth16VerifierId = GROTH16_VERIFIER_ID;
  const verifierRouterId = VERIFIER_ROUTER_ID;
  const GROTH16_SELECTOR = parseSelectorFromFixture(fixture.selector);

  let routerPda: PublicKey;
  let verifierEntryPda: PublicKey;

  const blockTimeForwarderId = new PublicKey("J1YYaBphwHzvGDq6EGY71DfPkuKWxMtHrtzGMUHp1LZ6");

  before(async () => {
    [routerPda] = getRouterPda(verifierRouterId);
    [verifierEntryPda] = getVerifierEntryPda(GROTH16_SELECTOR, verifierRouterId);

    // Lower min_expiry_slots to 10 so we can create short-lived TxData
    await program.methods
      .updateExpiryConfig(new anchor.BN(10), new anchor.BN(216_000))
      .accounts({
        paState,
        authority: provider.wallet.publicKey,
      })
      .rpc();
  });

  after(async () => {
    // Restore default config
    await program.methods
      .updateExpiryConfig(new anchor.BN(100), new anchor.BN(216_000))
      .accounts({
        paState,
        authority: provider.wallet.publicKey,
      })
      .rpc();
  });

  it("rejects txdata_write on expired TxData", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 12);

    // Create TxData with short expiry
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Write some data while still valid
    await program.methods
      .txdataWrite(uploadId, 0, Buffer.alloc(10))
      .accounts({
        txData,
        authority: authority.publicKey,
      })
      .signers([authority])
      .rpc();

    // Wait for expiry
    await waitForSlotPast(provider.connection, expiresSlot.toNumber());

    // Try to write again after expiry
    try {
      await program.methods
        .txdataWrite(uploadId, 10, Buffer.alloc(10))
        .accounts({
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
      assert.fail("expected txdata_write on expired TxData to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /TxDataExpired|has expired/i,
        `Expected TxDataExpired, got: ${haystack}`
      );
    }
  });

  it("rejects settle_from_txdata on expired TxData", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const tx = Buffer.from(fixture.tx_b64, "base64");
    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 12);

    // Create TxData with short expiry and write fixture data
    await program.methods
      .txdataInit(uploadId, tx.length, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    const chunkSize = 700;
    for (let offset = 0; offset < tx.length; offset += chunkSize) {
      const chunk = tx.subarray(offset, Math.min(tx.length, offset + chunkSize));
      await program.methods
        .txdataWrite(uploadId, offset, chunk)
        .accounts({
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
    }

    // Wait for expiry
    await waitForSlotPast(provider.connection, expiresSlot.toNumber());

    // Try to settle after expiry
    const nullifierPdas = fixture.consumed_nullifiers_b64.map((nfB64) => {
      const nf = Buffer.from(nfB64, "base64");
      return PublicKey.findProgramAddressSync(
        [NULLIFIER_SEED, paState.toBuffer(), nf],
        program.programId
      )[0];
    });

    const nullifierAccounts = nullifierPdas.map((pubkey) => ({
      pubkey,
      isWritable: true,
      isSigner: false,
    }));

    const allRemainingAccounts = [
      ...nullifierAccounts,
      { pubkey: blockTimeForwarderId, isWritable: false, isSigner: false },
      { pubkey: SYSVAR_CLOCK_PUBKEY, isWritable: false, isSigner: false },
    ];

    try {
      await program.methods
        .settleFromTxdata(uploadId)
        .accounts({
          paState,
          txData,
          authority: authority.publicKey,
          systemProgram: SystemProgram.programId,
          verifierRouterProgram: verifierRouterId,
          router: routerPda,
          verifierEntry: verifierEntryPda,
          verifierProgram: groth16VerifierId,
        })
        .remainingAccounts(allRemainingAccounts)
        .preInstructions([
          ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
          ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        ])
        .signers([authority])
        .rpc();
      assert.fail("expected settle_from_txdata on expired TxData to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /TxDataExpired|has expired/i,
        `Expected TxDataExpired, got: ${haystack}`
      );
    }
  });

  it("allows permissionless close of expired TxData", async () => {
    const authority = Keypair.generate();
    const cleaner = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);
    await airdrop(provider, cleaner.publicKey, 1);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 12);

    // Create TxData with short expiry
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Verify it exists
    const before = await provider.connection.getAccountInfo(txData);
    assert.ok(before, "TxData should exist before close");

    // Get refund balance before
    const refundBalanceBefore = await provider.connection.getBalance(authority.publicKey);

    // Wait for expiry
    await waitForSlotPast(provider.connection, expiresSlot.toNumber());

    // Third-party (cleaner) calls txdata_close_expired — permissionless
    await program.methods
      .txdataCloseExpired(uploadId, authority.publicKey)
      .accountsStrict({
        txData,
        payer: cleaner.publicKey,
        refund: authority.publicKey,
      })
      .signers([cleaner])
      .rpc();

    // Verify TxData no longer exists
    const after = await provider.connection.getAccountInfo(txData);
    assert.ok(!after, "TxData should not exist after close_expired");

    // Verify refund was sent to authority (not cleaner)
    const refundBalanceAfter = await provider.connection.getBalance(authority.publicKey);
    assert.ok(
      refundBalanceAfter > refundBalanceBefore,
      "Authority balance should increase after expired close (rent refund)"
    );
  });

  it("rejects txdata_extend with expires_slot too soon", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 12);

    // Create TxData
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Wait for the original expiry to pass so the extend would need to
    // satisfy bounds from current slot. Then try extending to current_slot + 5
    // which is below min_expiry_slots=10.
    await waitForSlotPast(provider.connection, expiresSlot.toNumber());

    const currentSlot = await provider.connection.getSlot("confirmed");
    const tooSoonExpiry = new anchor.BN(currentSlot + 5);

    try {
      await program.methods
        .txdataExtend(uploadId, tooSoonExpiry)
        .accountsStrict({
          paState,
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
      assert.fail("expected txdata_extend with expires_slot too soon to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /TxDataExpiryTooSoon|expires_slot is below minimum/i,
        `Expected TxDataExpiryTooSoon, got: ${haystack}`
      );
    }
  });

  it("rejects txdata_extend with expires_slot too late", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 1000);

    // Create TxData with valid expiry
    await program.methods
      .txdataInit(uploadId, 100, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    // Extend to way beyond max_expiry_slots (216_000)
    const currentSlot = await provider.connection.getSlot("confirmed");
    const tooLateExpiry = new anchor.BN(currentSlot + 216_000 + 100_000);

    try {
      await program.methods
        .txdataExtend(uploadId, tooLateExpiry)
        .accountsStrict({
          paState,
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
      assert.fail("expected txdata_extend with expires_slot too late to fail");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /TxDataExpiryTooLate|expires_slot exceeds maximum/i,
        `Expected TxDataExpiryTooLate, got: ${haystack}`
      );
    }
  });
});

// =============================================================================
// Emergency Stop E2E (MUST BE LAST — irreversible)
// =============================================================================
// Once emergency_stop is called, PAState is permanently paused. No further
// settle operations can succeed. This block MUST be the last describe in the file.

describe("solana-pa-prototype (Emergency Stop E2E — LAST)", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.SolanaPaPrototype as Program<SolanaPaPrototype>;

  const [paState] = PublicKey.findProgramAddressSync([PA_STATE_SEED], program.programId);

  const fixturePath = path.resolve(process.cwd(), "tests", "fixtures", "batch_groth16.json");
  const fixture = readJson<Fixture>(fixturePath);

  const groth16VerifierId = GROTH16_VERIFIER_ID;
  const verifierRouterId = VERIFIER_ROUTER_ID;
  const GROTH16_SELECTOR = parseSelectorFromFixture(fixture.selector);

  let routerPda: PublicKey;
  let verifierEntryPda: PublicKey;

  const blockTimeForwarderId = new PublicKey("J1YYaBphwHzvGDq6EGY71DfPkuKWxMtHrtzGMUHp1LZ6");

  before(async () => {
    [routerPda] = getRouterPda(verifierRouterId);
    [verifierEntryPda] = getVerifierEntryPda(GROTH16_SELECTOR, verifierRouterId);
  });

  it("emergency_stop pauses protocol", async () => {
    const stateBefore = await program.account.paStateAccount.fetch(paState);
    assert.equal(stateBefore.paused, false, "Should be unpaused before emergency_stop");

    await program.methods
      .emergencyStop()
      .accounts({
        paState,
        authority: provider.wallet.publicKey,
      })
      .rpc();

    const stateAfter = await program.account.paStateAccount.fetch(paState);
    assert.equal(stateAfter.paused, true, "Should be paused after emergency_stop");
  });

  it("rejects emergency_stop when already paused", async () => {
    try {
      await program.methods
        .emergencyStop()
        .accounts({
          paState,
          authority: provider.wallet.publicKey,
        })
        .rpc();
      assert.fail("expected emergency_stop to fail when already paused");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /AlreadyPaused|already paused/i,
        `Expected AlreadyPaused, got: ${haystack}`
      );
    }
  });

  it("rejects settle when paused", async () => {
    const payer = Keypair.generate();
    await airdrop(provider, payer.publicKey, 2);

    // Use a small garbage payload — the paused check fires before deserialization,
    // so any payload suffices. The full fixture is too large for a single settle instruction.
    try {
      await program.methods
        .settle(Buffer.from([0, 1, 2, 3]))
        .accounts({
          paState,
          payer: payer.publicKey,
          systemProgram: SystemProgram.programId,
          verifierRouterProgram: verifierRouterId,
          router: routerPda,
          verifierEntry: verifierEntryPda,
          verifierProgram: groth16VerifierId,
        })
        .preInstructions([
          ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
        ])
        .signers([payer])
        .rpc();
      assert.fail("expected settle to fail when paused");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /Paused|paused/i,
        `Expected Paused error, got: ${haystack}`
      );
    }
  });

  it("rejects settle_from_txdata when paused", async () => {
    const authority = Keypair.generate();
    await airdrop(provider, authority.publicKey, 2);

    const tx = Buffer.from(fixture.tx_b64, "base64");
    const { uploadId, uploadIdLe } = freshUploadId();

    const [txData] = PublicKey.findProgramAddressSync(
      [TX_DATA_SEED, authority.publicKey.toBuffer(), uploadIdLe],
      program.programId
    );

    const slot = await provider.connection.getSlot("confirmed");
    const expiresSlot = new anchor.BN(slot + 10_000);

    // Init and write TxData (these don't check paused state)
    await program.methods
      .txdataInit(uploadId, tx.length, expiresSlot)
      .accounts({
        paState,
        txData,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc();

    const chunkSize = 700;
    for (let offset = 0; offset < tx.length; offset += chunkSize) {
      const chunk = tx.subarray(offset, Math.min(tx.length, offset + chunkSize));
      await program.methods
        .txdataWrite(uploadId, offset, chunk)
        .accounts({
          txData,
          authority: authority.publicKey,
        })
        .signers([authority])
        .rpc();
    }

    const nullifierPdas = fixture.consumed_nullifiers_b64.map((nfB64) => {
      const nf = Buffer.from(nfB64, "base64");
      return PublicKey.findProgramAddressSync(
        [NULLIFIER_SEED, paState.toBuffer(), nf],
        program.programId
      )[0];
    });

    const nullifierAccounts = nullifierPdas.map((pubkey) => ({
      pubkey,
      isWritable: true,
      isSigner: false,
    }));

    const allRemainingAccounts = [
      ...nullifierAccounts,
      { pubkey: blockTimeForwarderId, isWritable: false, isSigner: false },
      { pubkey: SYSVAR_CLOCK_PUBKEY, isWritable: false, isSigner: false },
    ];

    try {
      await program.methods
        .settleFromTxdata(uploadId)
        .accounts({
          paState,
          txData,
          authority: authority.publicKey,
          systemProgram: SystemProgram.programId,
          verifierRouterProgram: verifierRouterId,
          router: routerPda,
          verifierEntry: verifierEntryPda,
          verifierProgram: groth16VerifierId,
        })
        .remainingAccounts(allRemainingAccounts)
        .preInstructions([
          ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
          ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        ])
        .signers([authority])
        .rpc();
      assert.fail("expected settle_from_txdata to fail when paused");
    } catch (e: any) {
      const haystack = errorHaystack(e);
      assert.match(
        haystack,
        /Paused|paused/i,
        `Expected Paused error, got: ${haystack}`
      );
    }
  });
});
