// Embedded passthrough guest artifact generated by risc0-build (methods.rs output).
pub const PASSTHROUGH_LOGIC_GUEST_ELF: &[u8] = include_bytes!("../elf/passthrough-logic-guest.bin");
pub const PASSTHROUGH_LOGIC_GUEST_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/elf/passthrough-logic-guest.bin"
);
pub const PASSTHROUGH_LOGIC_GUEST_ID: [u32; 8] = [
    1746697962, 3424054625, 581829347, 1654065497, 2538318772, 4069528050, 2287436122, 2799611956,
];
