use anchor_lang::prelude::*;

// localnet id automatically generated by `anchor build`.
declare_id!("28Hvr1YFv2ouGN2fS99aF3ZzYXzkncJVVaHcZNhquLFT");

#[cfg(all(
    feature = "custom-heap",
    target_os = "solana",
    not(feature = "no-entrypoint")
))]
#[global_allocator]
static GLOBAL_ALLOCATOR: CustomHeapAllocator = CustomHeapAllocator;

#[cfg(all(
    feature = "custom-heap",
    target_os = "solana",
    not(feature = "no-entrypoint")
))]
struct CustomHeapAllocator;

#[cfg(all(
    feature = "custom-heap",
    target_os = "solana",
    not(feature = "no-entrypoint")
))]
unsafe impl std::alloc::GlobalAlloc for CustomHeapAllocator {
    #[inline]
    unsafe fn alloc(&self, layout: std::alloc::Layout) -> *mut u8 {
        const EXTENDED_HEAP_BYTES: usize = 256 * 1024;

        let heap_start = anchor_lang::solana_program::entrypoint::HEAP_START_ADDRESS as usize;
        let default_heap_end = heap_start + anchor_lang::solana_program::entrypoint::HEAP_LENGTH;
        let extended_heap_end = heap_start + EXTENDED_HEAP_BYTES;
        let state_end = heap_start + std::mem::size_of::<usize>();
        let pos_ptr = heap_start as *mut usize;

        let current_pos = *pos_ptr;
        let pos = if current_pos == 0 {
            default_heap_end
        } else {
            current_pos
        };

        let floor = if pos > default_heap_end {
            default_heap_end
        } else {
            state_end
        };

        if let Some(next_pos) = allocate_from(pos, floor, layout) {
            *pos_ptr = next_pos;
            return next_pos as *mut u8;
        }

        if pos <= default_heap_end {
            if let Some(next_pos) = allocate_from(extended_heap_end, default_heap_end, layout) {
                *pos_ptr = next_pos;
                return next_pos as *mut u8;
            }
        }

        std::ptr::null_mut()
    }

    #[inline]
    unsafe fn dealloc(&self, _ptr: *mut u8, _layout: std::alloc::Layout) {}
}

#[cfg(all(
    feature = "custom-heap",
    target_os = "solana",
    not(feature = "no-entrypoint")
))]
#[inline]
fn allocate_from(pos: usize, floor: usize, layout: std::alloc::Layout) -> Option<usize> {
    let next_pos = pos.checked_sub(layout.size())? & !(layout.align().wrapping_sub(1));
    (next_pos >= floor).then_some(next_pos)
}

pub mod error;
mod events;
pub mod external_calls;
pub mod groth16;
pub mod marker;
pub mod merkle;
pub mod nullifier;
pub mod root;
pub mod settle;
pub mod state;
#[cfg(test)]
mod tests;
pub mod types;

use arm_core::aggregation_instance::AggregationInstance;
use arm_core::transaction::{Delta, Transaction};
pub use error::PAError;
use groth16::prepare_proof_for_verification;
use merkle::{append_to_tree, required_depth_for_leaves, MAX_TREE_DEPTH};
use state::*;

#[program]
pub mod protocol_adapter {
    use super::*;

    /// Initialize a new PAState account.
    ///
    /// Takes no remaining accounts. The empty-tree root equals `PADDING_LEAF`,
    /// which `is_root_valid` accepts unconditionally, so transactions built
    /// against the initial tree stay valid without a genesis marker.
    pub fn initialize<'info>(
        ctx: Context<'_, '_, '_, 'info, Initialize<'info>>,
        verifier_router: Pubkey,
        proof_selector: [u8; 4],
        kind_table_commitment: [u8; 32],
    ) -> Result<()> {
        let state = &mut ctx.accounts.pa_state;
        state.set_inner(PAStateAccount::running(
            ctx.bumps.pa_state,
            ctx.accounts.payer.key(),
            verifier_router,
            proof_selector,
            kind_table_commitment,
        ));

        msg!("PAState initialized with empty commitment tree");
        Ok(())
    }

    /// Settle a transaction: verify proofs, update commitment tree, mark nullifiers.
    pub fn settle<'info>(
        ctx: Context<'_, '_, '_, 'info, Settle<'info>>,
        transaction_data: Vec<u8>,
    ) -> Result<()> {
        require!(
            ctx.accounts.pa_state.lifecycle == PALifecycle::Running,
            PAError::Stopped
        );

        let tx: Transaction = bincode::deserialize(&transaction_data)
            .map_err(|_| error!(PAError::InvalidTransactionData))?;

        let pa_state_info = ctx.accounts.pa_state.to_account_info();
        let payer = ctx.accounts.payer.to_account_info();

        let events = events::EventCpi {
            authority: ctx.accounts.event_authority.to_account_info(),
            bump: ctx.bumps.event_authority,
        };

        execute_settlement(
            &mut ctx.accounts.pa_state,
            &pa_state_info,
            &tx,
            ctx.remaining_accounts,
            &payer,
            &ctx.accounts.system_program.to_account_info(),
            &ctx.accounts.new_root_marker.to_account_info(),
            VerifierAccounts {
                router_program: ctx.accounts.verifier_router_program.to_account_info(),
                router: ctx.accounts.router.to_account_info(),
                verifier_entry: ctx.accounts.verifier_entry.to_account_info(),
                verifier_program: ctx.accounts.verifier_program.to_account_info(),
            },
            &events,
        )?;

        msg!("Settlement complete");
        Ok(())
    }

    /// Initialize a TxData account for chunked upload.
    pub fn txdata_init(
        ctx: Context<TxDataInit>,
        upload_id: u64,
        capacity: u32,
        expires_slot: u64,
    ) -> Result<()> {
        let clock = Clock::get()?;
        validate_expiry_bounds(&ctx.accounts.pa_state, clock.slot, expires_slot)?;

        let txdata = &mut ctx.accounts.tx_data;
        txdata.bump = ctx.bumps.tx_data;
        txdata.authority = ctx.accounts.authority.key();
        txdata.refund = ctx.accounts.authority.key();
        txdata.written_len = 0;
        txdata.expires_slot = expires_slot;
        txdata.payload = vec![0u8; capacity as usize];

        msg!(
            "TxData initialized: upload_id={}, capacity={}, expires_slot={}",
            upload_id,
            capacity,
            expires_slot
        );
        Ok(())
    }

    /// Write a chunk to TxData.
    pub fn txdata_write(
        ctx: Context<TxDataWrite>,
        _upload_id: u64,
        offset: u32,
        data: Vec<u8>,
    ) -> Result<()> {
        let txdata = &mut ctx.accounts.tx_data;

        let clock = Clock::get()?;
        require!(clock.slot <= txdata.expires_slot, PAError::TxDataExpired);

        txdata.write_chunk(offset, &data)?;

        msg!("TxData write: {} bytes at offset {}", data.len(), offset);
        Ok(())
    }

    /// Close a TxData account and reclaim rent.
    pub fn txdata_close(_ctx: Context<TxDataClose>, upload_id: u64) -> Result<()> {
        msg!("TxData closed: upload_id={}", upload_id);
        Ok(())
    }

    /// Extend the expiration deadline of a TxData account.
    pub fn txdata_extend(
        ctx: Context<TxDataExtend>,
        upload_id: u64,
        new_expires_slot: u64,
    ) -> Result<()> {
        let clock = Clock::get()?;
        validate_expiry_bounds(&ctx.accounts.pa_state, clock.slot, new_expires_slot)?;

        let txdata = &mut ctx.accounts.tx_data;

        // New expiry must be strictly greater than current (prevent no-op or shortening)
        require!(
            new_expires_slot > txdata.expires_slot,
            PAError::TxDataExtendMustIncrease
        );

        let old_expires = txdata.expires_slot;
        txdata.expires_slot = new_expires_slot;

        msg!(
            "TxData extended: upload_id={}, old_expires={}, new_expires={}",
            upload_id,
            old_expires,
            new_expires_slot
        );
        Ok(())
    }

    /// Close an expired TxData account. Anyone can call; rent goes to `refund`.
    pub fn txdata_close_expired(
        ctx: Context<TxDataCloseExpired>,
        upload_id: u64,
        _authority: Pubkey,
    ) -> Result<()> {
        let clock = Clock::get()?;
        let txdata = &ctx.accounts.tx_data;

        require!(clock.slot > txdata.expires_slot, PAError::TxDataNotExpired);

        msg!(
            "Expired TxData closed: upload_id={}, expires_slot={}, current_slot={}",
            upload_id,
            txdata.expires_slot,
            clock.slot
        );
        Ok(())
    }

    /// Update TxData expiry configuration (authority only).
    pub fn update_expiry_config(
        ctx: Context<UpdateExpiryConfig>,
        new_min_expiry_slots: u64,
        new_max_expiry_slots: u64,
    ) -> Result<()> {
        require!(
            new_min_expiry_slots < new_max_expiry_slots,
            PAError::InvalidExpiryConfig
        );
        require!(
            new_min_expiry_slots >= MIN_ALLOWED_EXPIRY,
            PAError::InvalidExpiryConfig
        );
        require!(
            new_max_expiry_slots <= SEVEN_DAYS_SLOTS,
            PAError::InvalidExpiryConfig
        );

        let state = &mut ctx.accounts.pa_state;
        let old_min = state.min_expiry_slots;
        let old_max = state.max_expiry_slots;

        state.min_expiry_slots = new_min_expiry_slots;
        state.max_expiry_slots = new_max_expiry_slots;

        msg!(
            "Expiry config updated: min {} -> {}, max {} -> {}",
            old_min,
            new_min_expiry_slots,
            old_max,
            new_max_expiry_slots
        );
        Ok(())
    }

    /// Execute settlement from a TxData account.
    pub fn settle_from_txdata<'info>(
        ctx: Context<'_, '_, '_, 'info, SettleFromTxData<'info>>,
        _upload_id: u64,
    ) -> Result<()> {
        require!(
            ctx.accounts.pa_state.lifecycle == PALifecycle::Running,
            PAError::Stopped
        );

        let txdata = &ctx.accounts.tx_data;

        let clock = Clock::get()?;
        require!(clock.slot <= txdata.expires_slot, PAError::TxDataExpired);

        let tx: Transaction = bincode::deserialize(&txdata.payload[..txdata.written_len as usize])
            .map_err(|_| error!(PAError::InvalidTransactionData))?;

        let pa_state_info = ctx.accounts.pa_state.to_account_info();
        let payer = ctx.accounts.authority.to_account_info();

        let events = events::EventCpi {
            authority: ctx.accounts.event_authority.to_account_info(),
            bump: ctx.bumps.event_authority,
        };

        execute_settlement(
            &mut ctx.accounts.pa_state,
            &pa_state_info,
            &tx,
            ctx.remaining_accounts,
            &payer,
            &ctx.accounts.system_program.to_account_info(),
            &ctx.accounts.new_root_marker.to_account_info(),
            VerifierAccounts {
                router_program: ctx.accounts.verifier_router_program.to_account_info(),
                router: ctx.accounts.router.to_account_info(),
                verifier_entry: ctx.accounts.verifier_entry.to_account_info(),
                verifier_program: ctx.accounts.verifier_program.to_account_info(),
            },
            &events,
        )?;

        msg!("Settlement from TxData complete");
        Ok(())
    }

    /// Emergency stop — terminal. Retires this deployment permanently.
    ///
    /// There is no resume instruction: `Running` is set only at initialization
    /// and this is the only transition out of it. Recovery from a stop is
    /// migration to a new deployment, matching the EVM adapter, which has no
    /// unpause and whose contract is not upgradeable.
    ///
    /// Solana programs are upgradeable, so the runtime does not enforce
    /// terminality the way EVM immutability does — that boundary is
    /// operational, not on-chain. `close_markers_batch` exists only in
    /// `dev-teardown` builds (never present in production) to reclaim marker
    /// rent so a *development* deployment can be re-initialized in place; it
    /// has no production counterpart. Reclaiming marker rent has no
    /// dependency on the upgrade authority.
    ///
    /// A production shutdown of this deployment is a separate, later step:
    /// setting `program_data.upgrade_authority_address` to `None` makes the
    /// program immutable. Do that only once the deployment is truly retired,
    /// because `initialize` requires
    /// `program_data.upgrade_authority_address == Some(payer.key())` — once
    /// the authority is `None`, this program ID can never be initialized
    /// again, even after `close-pa-state`.
    pub fn emergency_stop(ctx: Context<EmergencyStop>) -> Result<()> {
        let state = &mut ctx.accounts.pa_state;
        require!(
            state.lifecycle == PALifecycle::Running,
            PAError::AlreadyStopped
        );
        state.lifecycle = PALifecycle::Stopped;
        msg!(
            "Emergency stop activated by {}",
            ctx.accounts.authority.key()
        );
        Ok(())
    }

    /// Propose a new authority. The transfer is not effective until the
    /// proposed authority calls `accept_authority`.
    pub fn propose_authority(ctx: Context<ProposeAuthority>, new_authority: Pubkey) -> Result<()> {
        let state = &mut ctx.accounts.pa_state;
        state.pending_authority = Some(new_authority);
        msg!(
            "Authority transfer proposed: {} -> {}",
            state.authority,
            new_authority
        );
        Ok(())
    }

    /// Accept a pending authority transfer. Must be signed by the proposed
    /// authority. Completes the two-step transfer.
    pub fn accept_authority(ctx: Context<AcceptAuthority>) -> Result<()> {
        let state = &mut ctx.accounts.pa_state;
        let new_authority = state.pending_authority.ok_or(PAError::NoPendingAuthority)?;
        require!(
            ctx.accounts.new_authority.key() == new_authority,
            PAError::Unauthorized
        );
        let old_authority = state.authority;
        state.authority = new_authority;
        state.pending_authority = None;
        msg!(
            "Authority transferred: {} -> {}",
            old_authority,
            new_authority
        );
        Ok(())
    }

    /// Cancel a pending authority transfer. Only callable by the current authority.
    pub fn cancel_authority_transfer(ctx: Context<CancelAuthorityTransfer>) -> Result<()> {
        let state = &mut ctx.accounts.pa_state;
        require!(
            state.pending_authority.is_some(),
            PAError::NoPendingAuthority
        );
        state.pending_authority = None;
        msg!("Pending authority transfer cancelled");
        Ok(())
    }

    /// Close marker PDAs and reclaim their rent. Development tooling only.
    ///
    /// Deleting nullifier markers destroys replay protection, and re-initializing
    /// reuses the same `pa_state` address and therefore the same marker
    /// addresses, so previously spent nullifiers become spendable again. That is
    /// the point during development and must be impossible in production, so this
    /// instruction is absent unless `dev-teardown` is enabled.
    #[cfg(feature = "dev-teardown")]
    pub fn close_markers_batch<'info>(
        ctx: Context<'_, '_, '_, 'info, CloseMarkersBatch<'info>>,
    ) -> Result<()> {
        require!(
            ctx.accounts.pa_state.lifecycle == PALifecycle::Stopped,
            PAError::NotStopped
        );
        let authority_info = ctx.accounts.authority.to_account_info();
        for marker in ctx.remaining_accounts {
            require!(marker.owner == &crate::ID, PAError::InvalidMarker);
            require!(marker.data_is_empty(), PAError::InvalidMarker);
            let marker_lamports = marker.lamports();
            **marker.lamports.borrow_mut() = 0;
            **authority_info.lamports.borrow_mut() = authority_info
                .lamports()
                .checked_add(marker_lamports)
                .unwrap();
            marker.assign(&anchor_lang::solana_program::system_program::ID);
        }
        msg!("Closed {} markers", ctx.remaining_accounts.len());
        Ok(())
    }

    /// Overwrite the state account's schema version. Development tooling only:
    /// lets the integration suite observe every instruction refuse a foreign
    /// version. Carries no version constraint, since like a migration it must
    /// accept one; the typed load works only because the byte flip keeps the layout.
    #[cfg(feature = "dev-teardown")]
    pub fn dev_set_schema_version(ctx: Context<DevSetSchemaVersion>, version: u8) -> Result<()> {
        ctx.accounts.pa_state.schema_version = version;
        msg!("PAState schema version set to {}", version);
        Ok(())
    }
}

/// Floor at 1 lamport because 0-lamport accounts can be garbage-collected.
fn marker_lamports(rent: &Rent) -> u64 {
    rent.minimum_balance(0).max(1)
}

/// Accounts needed for the verifier_router CPI.
struct VerifierAccounts<'info> {
    router_program: AccountInfo<'info>,
    router: AccountInfo<'info>,
    verifier_entry: AccountInfo<'info>,
    verifier_program: AccountInfo<'info>,
}

/// Validate that an expiry slot falls within the configurable bounds.
fn validate_expiry_bounds(
    pa_state: &PAStateAccount,
    current_slot: u64,
    expires_slot: u64,
) -> Result<()> {
    let min_expires = current_slot.saturating_add(pa_state.min_expiry_slots);
    let max_expires = current_slot.saturating_add(pa_state.max_expiry_slots);
    require!(expires_slot >= min_expires, PAError::TxDataExpiryTooSoon);
    require!(expires_slot <= max_expires, PAError::TxDataExpiryTooLate);
    Ok(())
}

/// Reallocate PAState if tree growth is needed for the incoming commitments.
fn maybe_grow_account<'info>(
    pa_state_info: &AccountInfo<'info>,
    state: &PAStateAccount,
    num_commitments: usize,
    payer: &AccountInfo<'info>,
    system_program: &AccountInfo<'info>,
    rent: &Rent,
) -> Result<()> {
    let final_next_index = state.next_index.saturating_add(num_commitments as u64);
    let required_depth = required_depth_for_leaves(final_next_index);

    // Cap at MAX_TREE_DEPTH (append_to_tree will error if exceeded)
    let target_depth = required_depth.min(MAX_TREE_DEPTH);

    if target_depth <= state.depth() {
        return Ok(());
    }

    let new_size = PAStateAccount::space_for_depth(target_depth);
    let new_minimum_balance = rent.minimum_balance(new_size);
    let current_balance = pa_state_info.lamports();

    // Transfer additional lamports if needed (before realloc)
    if new_minimum_balance > current_balance {
        let lamports_needed = new_minimum_balance - current_balance;
        anchor_lang::system_program::transfer(
            CpiContext::new(
                system_program.clone(),
                anchor_lang::system_program::Transfer {
                    from: payer.clone(),
                    to: pa_state_info.clone(),
                },
            ),
            lamports_needed,
        )?;
    }

    // Resize the account data
    pa_state_info.resize(new_size)?;

    msg!(
        "Reallocated PAState: depth {} -> {}",
        state.depth(),
        target_depth
    );
    Ok(())
}

/// Require every root consumed by the instance to be one the adapter accepts.
///
/// Takes `state` by shared reference on purpose: validation must not be able to
/// mutate adapter state. `execute_settlement` holds `&mut PAStateAccount` for its
/// whole body, so without this narrowing the compiler would permit a mutation here
/// and the ordering would rest on what happens to be written rather than on what
/// is allowed.
fn validate_consumed_roots(
    instance: &AggregationInstance,
    state: &PAStateAccount,
    pa_state_key: &Pubkey,
    remaining_accounts: &[AccountInfo],
) -> Result<()> {
    for root in &settle::unique_consumed_roots(instance) {
        require!(
            root::is_root_valid(state, &crate::ID, pa_state_key, root, remaining_accounts),
            PAError::NonExistingRoot
        );
    }
    Ok(())
}

/// Shared settlement logic for both settle and settle_from_txdata.
///
/// `remaining_accounts` layout:
///   [0..nullifier_count]  — nullifier marker PDAs (created by this function)
///   [nullifier_count..N]  — external call forwarder segments (program + CPI accounts)
///
/// Historical root marker PDAs are found by key scan, so they may appear at any index.
/// The marker for the root this settlement produces is a separate named account
/// (`new_root_marker`), not part of `remaining_accounts`.
///
/// The account parameters are individually threaded (rather than grouped into a
/// struct) because each is used independently and at a different point in the
/// function body; grouping would not reduce the real complexity, only relocate it.
#[allow(clippy::too_many_arguments)]
fn execute_settlement<'info>(
    state: &mut PAStateAccount,
    pa_state_info: &AccountInfo<'info>,
    tx: &Transaction,
    remaining_accounts: &[AccountInfo<'info>],
    payer: &AccountInfo<'info>,
    system_program: &AccountInfo<'info>,
    new_root_marker: &AccountInfo<'info>,
    verifier: VerifierAccounts<'info>,
    events: &events::EventCpi<'info>,
) -> Result<()> {
    let pa_state_key = pa_state_info.key;

    // The instance is the only proof-backed source of settlement data;
    // `require_aggregation` also rejects the ambiguous shape carrying both
    // base actions and an aggregation.
    let aggregation = tx
        .aggregation
        .as_ref()
        .ok_or_else(|| error!(PAError::AggregationRequired))?;
    let instance = arm_solana::journal::require_aggregation(tx).map_err(PAError::from)?;

    // A witness delta is prover-side private data; settling it would both
    // leak it on-chain and prove nothing. Reject before any other work.
    let delta_proof = match &tx.delta_proof {
        Delta::Proof(proof) => proof,
        Delta::Witness(_) => return Err(error!(PAError::ExpectedDeltaProof)),
    };

    require!(
        !instance.actions.is_empty(),
        PAError::InvalidTransactionData
    );

    // The aggregation guest verifies compliance proofs against whatever
    // compliance key the prover supplied; pinning it here is what ties the
    // settlement to *the* compliance circuit.
    require!(
        instance.compliance_key == arm_core::constants::COMPLIANCE_VK,
        PAError::ComplianceKeyMismatch
    );
    require!(
        instance.kind_table_commitment == arm_core::Digest::from_bytes(state.kind_table_commitment),
        PAError::KindTableCommitmentMismatch
    );
    instance
        .nf_duplication_check()
        .map_err(|_| error!(PAError::NullifierDuplication))?;

    validate_consumed_roots(instance, state, pa_state_key, remaining_accounts)?;

    let nullifiers = settle::extract_nullifiers(instance);

    let prepared = prepare_proof_for_verification(aggregation, state.proof_selector)
        .map_err(|e| -> anchor_lang::error::Error { e.into() })?;

    msg!("Verifying aggregated proof via verifier_router");
    {
        let cpi_accounts = verifier_router::cpi::accounts::Verify {
            router: verifier.router.clone(),
            verifier_entry: verifier.verifier_entry.clone(),
            verifier_program: verifier.verifier_program.clone(),
            system_program: system_program.clone(),
        };
        let cpi_ctx = CpiContext::new(verifier.router_program.clone(), cpi_accounts);
        verifier_router::cpi::verify(
            cpi_ctx,
            prepared.seal,
            prepared.image_id,
            prepared.journal_digest,
        )
        .map_err(|_| error!(PAError::VerifierRouterFailed))?;
    }

    arm_solana::delta::verify_delta_proof_with_instance(delta_proof, instance)
        .map_err(PAError::from)?;

    // Events enable off-chain indexers to reconstruct action/transaction data.
    // Order is the instance order the proof commits to: actions in sequence,
    // consumed resources before created resources within each action.
    let total_tag_count = settle::total_resource_count(instance);
    let mut all_tags: Vec<[u8; 32]> = Vec::with_capacity(total_tag_count);
    let mut all_logic_refs: Vec<[u8; 32]> = Vec::with_capacity(total_tag_count);
    let mut all_is_consumed: Vec<bool> = Vec::with_capacity(total_tag_count);

    for action in &instance.actions {
        for resource in settle::action_resources(action) {
            emit_app_data_events(events, &resource.tag, resource.app_data)?;
            all_tags.push(resource.tag.into());
            all_logic_refs.push(resource.logic_ref.into());
            all_is_consumed.push(resource.is_consumed);
        }

        events.emit(&ActionExecutedEvent {
            action_tree_root: action.action_tree_root.into(),
            action_tag_count: settle::action_resource_count(action) as u32,
        })?;
    }

    // Runs before nullifier and commitment state changes so that a forwarder
    // cannot observe them. Solana reverts every account write when the
    // instruction returns Err, so partial state on failure is impossible
    // regardless of ordering — that is not what this ordering protects. The
    // forwarder is chosen by the proof and runs while the transaction is still
    // in flight, and it can read any account it is handed; running it first
    // bounds what this settlement has written by the time it executes.
    #[cfg(not(test))]
    for event in
        external_calls::execute_external_calls(instance, remaining_accounts, nullifiers.len())
            .map_err(anchor_lang::error::Error::from)?
    {
        events.emit(&event)?;
    }

    // Emit TransactionExecuted event (EVM parity). `is_consumed` states each
    // tag's role explicitly — consumed and created resources are grouped per
    // action rather than alternating, so parity cannot infer it.
    events.emit(&TransactionExecutedEvent {
        tags: all_tags,
        logic_refs: all_logic_refs,
        is_consumed: all_is_consumed,
    })?;

    let rent = Rent::get()?;
    let ml = marker_lamports(&rent);

    if !nullifiers.is_empty() {
        require!(
            remaining_accounts.len() >= nullifiers.len(),
            PAError::InvalidTransactionData
        );

        for (i, nullifier) in nullifiers.iter().enumerate() {
            let marker = &remaining_accounts[i];
            let nullifier_bytes: [u8; 32] = (*nullifier).into();
            nullifier::check_and_create_nullifier_marker(
                &crate::ID,
                pa_state_key,
                &nullifier_bytes,
                payer,
                marker,
                system_program,
                ml,
            )?;
        }
        msg!("Created {} nullifier PDAs", nullifiers.len());
    }

    let commitments = settle::extract_commitments(instance);
    maybe_grow_account(
        pa_state_info,
        state,
        commitments.len(),
        payer,
        system_program,
        &rent,
    )?;
    for commitment in commitments {
        append_to_tree(state, commitment)?;
    }

    let new_root = state.root;

    // Every state-changing settlement must retain its resulting root so that
    // concurrently constructed transactions remain valid after the tree advances.
    // Solana cannot create an undeclared account, so the marker is required and a
    // settlement that omits it is rejected.
    let (expected_pda, _) = root::derive_root_pda(&crate::ID, pa_state_key, &new_root);
    require_keys_eq!(expected_pda, *new_root_marker.key, PAError::RootPdaMismatch);
    root::create_root_marker(
        &crate::ID,
        pa_state_key,
        &new_root,
        payer,
        new_root_marker,
        system_program,
        ml,
    )?;
    msg!("Created root marker for new root");

    Ok(())
}

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = payer,
        space = PAStateAccount::INITIAL_SPACE, // Variable-depth tree starts at depth 1
        seeds = [PA_STATE_SEED],
        bump
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(mut)]
    pub payer: Signer<'info>,

    pub system_program: Program<'info, System>,

    /// The program account is required so `program_data` is proven to be
    /// *this* program's ProgramData address rather than merely an account
    /// shaped like one: the constraint reads the programdata address the
    /// loader recorded inside this very program account and requires it to
    /// match the supplied `program_data` account.
    #[account(constraint = program.programdata_address()? == Some(program_data.key()) @ PAError::Unauthorized)]
    pub program: Program<'info, crate::program::ProtocolAdapter>,

    /// The loader records the upgrade authority here at deploy time, which is the
    /// only trust anchor available before the adapter has any state of its own.
    #[account(
        constraint = program_data.upgrade_authority_address == Some(payer.key())
            @ PAError::Unauthorized
    )]
    pub program_data: Account<'info, ProgramData>,
}

#[derive(Accounts)]
pub struct EmergencyStop<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        has_one = authority @ PAError::Unauthorized,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    pub authority: Signer<'info>,
}

#[derive(Accounts)]
pub struct ProposeAuthority<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        has_one = authority @ PAError::Unauthorized,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    pub authority: Signer<'info>,
}

#[derive(Accounts)]
pub struct AcceptAuthority<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    pub new_authority: Signer<'info>,
}

#[derive(Accounts)]
pub struct CancelAuthorityTransfer<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        has_one = authority @ PAError::Unauthorized,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    pub authority: Signer<'info>,
}

#[event_cpi]
#[derive(Accounts)]
pub struct Settle<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(mut)]
    pub payer: Signer<'info>,
    pub system_program: Program<'info, System>,

    /// CHECK: Validated at runtime against the root produced by this settlement.
    /// Cannot use a seeds constraint: the address depends on the resulting root,
    /// which is only known after commitments are appended.
    #[account(mut)]
    pub new_root_marker: UncheckedAccount<'info>,

    /// CHECK: Validated against verifier_router stored in PAStateAccount.
    #[account(constraint = verifier_router_program.key() == pa_state.verifier_router @ PAError::VerifierRouterFailed)]
    pub verifier_router_program: UncheckedAccount<'info>,

    /// CHECK: Router state PDA - validated by verifier_router during CPI.
    pub router: UncheckedAccount<'info>,

    /// CHECK: Verifier entry PDA - validated by verifier_router during CPI.
    pub verifier_entry: UncheckedAccount<'info>,

    /// CHECK: The groth16 verifier program - validated by verifier_router.
    pub verifier_program: UncheckedAccount<'info>,
}

#[event_cpi]
#[derive(Accounts)]
#[instruction(upload_id: u64)]
pub struct SettleFromTxData<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        has_one = authority @ PAError::Unauthorized
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    #[account(mut)]
    pub authority: Signer<'info>,
    pub system_program: Program<'info, System>,

    /// CHECK: Validated at runtime against the root produced by this settlement.
    /// Cannot use a seeds constraint: the address depends on the resulting root,
    /// which is only known after commitments are appended.
    #[account(mut)]
    pub new_root_marker: UncheckedAccount<'info>,

    /// CHECK: Validated against verifier_router stored in PAStateAccount.
    #[account(constraint = verifier_router_program.key() == pa_state.verifier_router @ PAError::VerifierRouterFailed)]
    pub verifier_router_program: UncheckedAccount<'info>,

    /// CHECK: Router state PDA - validated by verifier_router during CPI.
    pub router: UncheckedAccount<'info>,

    /// CHECK: Verifier entry PDA - validated by verifier_router during CPI.
    pub verifier_entry: UncheckedAccount<'info>,

    /// CHECK: The groth16 verifier program - validated by verifier_router.
    pub verifier_program: UncheckedAccount<'info>,
    // remaining_accounts: nullifier PDAs + external call accounts
}

#[derive(Accounts)]
#[instruction(upload_id: u64, capacity: u32)]
pub struct TxDataInit<'info> {
    /// PAState for reading configurable expiry bounds.
    #[account(
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(
        init,
        payer = authority,
        space = TxDataAccount::space(capacity as usize),
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    #[account(mut)]
    pub authority: Signer<'info>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(upload_id: u64)]
pub struct TxDataWrite<'info> {
    #[account(
        mut,
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        has_one = authority @ PAError::Unauthorized
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    pub authority: Signer<'info>,
}

#[derive(Accounts)]
#[instruction(upload_id: u64)]
pub struct TxDataClose<'info> {
    #[account(
        mut,
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        has_one = authority @ PAError::Unauthorized,
        close = refund
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    pub authority: Signer<'info>,

    /// CHECK: Receives the rent refund. Must match tx_data.refund.
    #[account(mut, address = tx_data.refund)]
    pub refund: UncheckedAccount<'info>,
}

#[derive(Accounts)]
#[instruction(upload_id: u64)]
pub struct TxDataExtend<'info> {
    /// PAState for reading configurable expiry bounds.
    #[account(
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(
        mut,
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        has_one = authority @ PAError::Unauthorized
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    pub authority: Signer<'info>,
}

#[derive(Accounts)]
#[instruction(upload_id: u64, authority: Pubkey)]
pub struct TxDataCloseExpired<'info> {
    #[account(
        mut,
        seeds = [TX_DATA_SEED, authority.as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        close = refund
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    /// Anyone can call, pays tx fee.
    pub payer: Signer<'info>,

    /// CHECK: Receives the rent refund. Must match tx_data.refund.
    #[account(mut, address = tx_data.refund)]
    pub refund: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct UpdateExpiryConfig<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        has_one = authority @ PAError::Unauthorized,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    pub authority: Signer<'info>,
}

#[cfg(feature = "dev-teardown")]
#[derive(Accounts)]
pub struct CloseMarkersBatch<'info> {
    #[account(
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        has_one = authority @ PAError::Unauthorized,
        constraint = pa_state.schema_version == PAStateAccount::SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(mut)]
    pub authority: Signer<'info>,
}

#[cfg(feature = "dev-teardown")]
#[derive(Accounts)]
pub struct DevSetSchemaVersion<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        has_one = authority @ PAError::Unauthorized,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    pub authority: Signer<'info>,
}

// Four separate event structs with identical fields: each produces a distinct Anchor
// discriminator (sha256 of the struct name), enabling indexers to filter by payload
// category at the log-parsing level without decoding the event body.
#[event]
pub struct ResourcePayloadEvent {
    pub tag: [u8; 32],
    pub index: u32,
    pub blob: Vec<u8>,
}

#[event]
pub struct DiscoveryPayloadEvent {
    pub tag: [u8; 32],
    pub index: u32,
    pub blob: Vec<u8>,
}

#[event]
pub struct ExternalPayloadEvent {
    pub tag: [u8; 32],
    pub index: u32,
    pub blob: Vec<u8>,
}

#[event]
pub struct ApplicationPayloadEvent {
    pub tag: [u8; 32],
    pub index: u32,
    pub blob: Vec<u8>,
}

/// Matches EVM PA's ActionExecuted event.
#[event]
pub struct ActionExecutedEvent {
    pub action_tree_root: [u8; 32],
    pub action_tag_count: u32,
}

/// Matches EVM PA's TransactionExecuted event, with each tag's role stated
/// explicitly: `is_consumed[i]` is true when `tags[i]` is a nullifier and
/// false when it is a commitment.
#[event]
pub struct TransactionExecutedEvent {
    pub tags: Vec<[u8; 32]>,
    pub logic_refs: Vec<[u8; 32]>,
    pub is_consumed: Vec<bool>,
}

/// Matches EVM PA's ForwarderCallExecuted event.
#[event]
pub struct ForwarderCallExecutedEvent {
    pub forwarder: Pubkey,
    pub input: Vec<u8>,
    pub output: Vec<u8>,
}

fn emit_app_data_events(
    events: &events::EventCpi,
    tag: &arm_core::Digest,
    app_data: &arm_core::logic_instance::AppData,
) -> Result<()> {
    let tag_bytes: [u8; 32] = (*tag).into();

    macro_rules! emit_payloads {
        ($payloads:expr, $Event:ident) => {
            for (i, payload) in $payloads.iter().enumerate() {
                if payload.deletion_criterion == DELETION_CRITERION_NEVER {
                    events.emit(&$Event {
                        tag: tag_bytes,
                        index: i as u32,
                        blob: arm_core::utils::words_to_bytes(&payload.blob).to_vec(),
                    })?;
                }
            }
        };
    }

    emit_payloads!(app_data.resource_payload, ResourcePayloadEvent);
    emit_payloads!(app_data.discovery_payload, DiscoveryPayloadEvent);
    emit_payloads!(app_data.external_payload, ExternalPayloadEvent);
    emit_payloads!(app_data.application_payload, ApplicationPayloadEvent);
    Ok(())
}
