use anchor_lang::prelude::*;

// localnet id automatically generated by `anchor build`.
declare_id!("5zeqkB3kc9fd1RvaXB2GeMB53Jgf98QJtaFK38e6tTsc");

// CPI client and types of the RISC Zero verifier router, generated from
// idls/verifier_router.json: the IDL of risc0/risc0-solana v3.0.0 (ee415935),
// the release the deployed verifiers run, built from that source with its
// Anchor 0.31.1 (the IDL committed in that repository is stale). The
// real-mode suite exercises it against the deployed router.
declare_program!(verifier_router);

#[cfg(all(
    feature = "custom-heap",
    target_os = "solana",
    not(feature = "no-entrypoint")
))]
#[global_allocator]
static GLOBAL_ALLOCATOR: CustomHeapAllocator = CustomHeapAllocator;

#[cfg(all(
    feature = "custom-heap",
    target_os = "solana",
    not(feature = "no-entrypoint")
))]
struct CustomHeapAllocator;

#[cfg(all(
    feature = "custom-heap",
    target_os = "solana",
    not(feature = "no-entrypoint")
))]
unsafe impl std::alloc::GlobalAlloc for CustomHeapAllocator {
    #[inline]
    unsafe fn alloc(&self, layout: std::alloc::Layout) -> *mut u8 {
        const EXTENDED_HEAP_BYTES: usize = 256 * 1024;

        let heap_start = anchor_lang::solana_program::entrypoint::HEAP_START_ADDRESS as usize;
        let default_heap_end = heap_start + anchor_lang::solana_program::entrypoint::HEAP_LENGTH;
        let extended_heap_end = heap_start + EXTENDED_HEAP_BYTES;
        let state_end = heap_start + std::mem::size_of::<usize>();
        let pos_ptr = heap_start as *mut usize;

        let current_pos = *pos_ptr;
        let pos = if current_pos == 0 {
            default_heap_end
        } else {
            current_pos
        };

        let floor = if pos > default_heap_end {
            default_heap_end
        } else {
            state_end
        };

        if let Some(next_pos) = allocate_from(pos, floor, layout) {
            *pos_ptr = next_pos;
            return next_pos as *mut u8;
        }

        if pos <= default_heap_end {
            if let Some(next_pos) = allocate_from(extended_heap_end, default_heap_end, layout) {
                *pos_ptr = next_pos;
                return next_pos as *mut u8;
            }
        }

        std::ptr::null_mut()
    }

    #[inline]
    unsafe fn dealloc(&self, _ptr: *mut u8, _layout: std::alloc::Layout) {}
}

#[cfg(all(
    feature = "custom-heap",
    target_os = "solana",
    not(feature = "no-entrypoint")
))]
#[inline]
fn allocate_from(pos: usize, floor: usize, layout: std::alloc::Layout) -> Option<usize> {
    let next_pos = pos.checked_sub(layout.size())? & !(layout.align().wrapping_sub(1));
    (next_pos >= floor).then_some(next_pos)
}

pub mod error;
mod events;
pub mod external_calls;
pub mod groth16;
pub mod marker;
pub mod merkle;
pub mod nullifier;
pub mod root;
pub mod settle;
pub mod state;
#[cfg(test)]
mod tests;
pub mod types;
pub mod upgrade;

use arm_core::aggregation_instance::AggregationInstance;
use arm_core::transaction::{Delta, Transaction};
pub use error::PAError;
use groth16::prepare_proof_for_verification;
use merkle::{append_to_tree, required_depth_for_leaves, EMPTY_TREE_ROOT_INITIAL, MAX_TREE_DEPTH};
use state::*;

#[program]
pub mod protocol_adapter {
    use super::*;

    /// Initialize a new PAState account, owned by `initial_owner`.
    ///
    /// Signed by the program's upgrade authority, the deployer, who alone may
    /// initialize it; it hands that authority to the program's
    /// `UPGRADE_AUTHORITY_SEED` PDA, so from then on only `upgrade`, for the
    /// owner, upgrades the program. Takes no remaining accounts. The
    /// empty-tree root equals `PADDING_LEAF`, which `is_root_valid` accepts
    /// unconditionally, so transactions built against the initial tree stay
    /// valid without a genesis marker. Like pa-evm's initializer, it sets the
    /// owner, starts on the empty kind table, and announces both;
    /// `set_kind_table_commitment` installs any other table.
    pub fn initialize<'info>(
        ctx: Context<'info, Initialize<'info>>,
        initial_owner: Pubkey,
        verifier_router: Pubkey,
        proof_selector: [u8; 4],
    ) -> Result<()> {
        require!(
            initial_owner != Pubkey::default(),
            PAError::OwnableInvalidOwner
        );
        require!(
            verifier_router != Pubkey::default(),
            PAError::ZeroVerifierRouterNotAllowed
        );
        require!(
            proof_selector != [0u8; 4],
            PAError::ZeroProofSelectorNotAllowed
        );
        // pa-evm's initializer's sanity check: the verifier is not paused already.
        require!(
            !verifier_paused(
                &ctx.accounts.verifier_entry,
                &verifier_router,
                proof_selector
            )?,
            PAError::RiscZeroVerifierPaused
        );
        ctx.accounts.pa_state.set_inner(PAStateAccount::running(
            ctx.bumps.pa_state,
            initial_owner,
            verifier_router,
            proof_selector,
        ));
        upgrade::hand_upgrade_authority_to_program(
            &crate::ID,
            ctx.bumps.upgrade_authority,
            &ctx.accounts.program_data.to_account_info(),
            &ctx.accounts.payer.to_account_info(),
            &ctx.accounts.upgrade_authority.to_account_info(),
            &ctx.accounts.bpf_loader_upgradeable.to_account_info(),
        )?;

        // pa-evm's initializer sets the owner (OwnableUpgradeable's
        // `OwnershipTransferred` from the zero address), adds the empty
        // tree's root, then installs the empty kind table.
        emit_cpi!(OwnershipTransferredEvent {
            previous_owner: Pubkey::default(),
            new_owner: initial_owner,
        });
        emit_cpi!(CommitmentTreeRootAddedEvent {
            root: EMPTY_TREE_ROOT_INITIAL.into(),
        });
        emit_cpi!(KindTableCommitmentUpdatedEvent {
            kind_table_commitment: EMPTY_KIND_TABLE_COMMITMENT,
        });

        msg!("PAState initialized with empty commitment tree");
        Ok(())
    }

    /// Settle a transaction: verify proofs, update commitment tree, mark nullifiers.
    pub fn settle<'info>(
        ctx: Context<'info, Settle<'info>>,
        transaction_data: Vec<u8>,
    ) -> Result<()> {
        require!(!ctx.accounts.pa_state.paused, PAError::EnforcedPause);

        let tx: Transaction = bincode::deserialize(&transaction_data)
            .map_err(|_| error!(PAError::InvalidTransactionData))?;

        let pa_state_info = ctx.accounts.pa_state.to_account_info();
        let payer = ctx.accounts.payer.to_account_info();

        let events = events::EventCpi {
            authority: ctx.accounts.event_authority.to_account_info(),
        };

        execute_settlement(
            &mut ctx.accounts.pa_state,
            &tx,
            SettlementAccounts {
                pa_state: pa_state_info,
                payer,
                system_program: ctx.accounts.system_program.to_account_info(),
                new_root_marker: ctx.accounts.new_root_marker.as_deref(),
                remaining: ctx.remaining_accounts,
                verifier: VerifierAccounts {
                    router_program_id: ctx.accounts.verifier_router_program.key(),
                    router: ctx.accounts.router.to_account_info(),
                    verifier_entry: ctx.accounts.verifier_entry.to_account_info(),
                    verifier_program: ctx.accounts.verifier_program.to_account_info(),
                },
                events,
            },
        )?;

        msg!("Settlement complete");
        Ok(())
    }

    /// Initialize a TxData account for chunked upload.
    pub fn txdata_init(
        ctx: Context<TxDataInit>,
        upload_id: u64,
        capacity: u32,
        expires_slot: u64,
    ) -> Result<()> {
        let clock = Clock::get()?;
        validate_expiry_bounds(&ctx.accounts.pa_state, clock.slot, expires_slot)?;

        let txdata = &mut ctx.accounts.tx_data;
        txdata.bump = ctx.bumps.tx_data;
        txdata.authority = ctx.accounts.authority.key();
        txdata.refund = ctx.accounts.authority.key();
        txdata.written_len = 0;
        txdata.expires_slot = expires_slot;
        txdata.payload = vec![0u8; capacity as usize];

        msg!(
            "TxData initialized: upload_id={}, capacity={}, expires_slot={}",
            upload_id,
            capacity,
            expires_slot
        );
        Ok(())
    }

    /// Write a chunk to TxData.
    pub fn txdata_write(
        ctx: Context<TxDataWrite>,
        _upload_id: u64,
        offset: u32,
        data: Vec<u8>,
    ) -> Result<()> {
        let txdata = &mut ctx.accounts.tx_data;

        let clock = Clock::get()?;
        require!(clock.slot <= txdata.expires_slot, PAError::TxDataExpired);

        txdata.write_chunk(offset, &data)?;

        msg!("TxData write: {} bytes at offset {}", data.len(), offset);
        Ok(())
    }

    /// Close a TxData account and reclaim rent.
    pub fn txdata_close(_ctx: Context<TxDataClose>, upload_id: u64) -> Result<()> {
        msg!("TxData closed: upload_id={}", upload_id);
        Ok(())
    }

    /// Extend the expiration deadline of a TxData account.
    pub fn txdata_extend(
        ctx: Context<TxDataExtend>,
        upload_id: u64,
        new_expires_slot: u64,
    ) -> Result<()> {
        let clock = Clock::get()?;
        validate_expiry_bounds(&ctx.accounts.pa_state, clock.slot, new_expires_slot)?;

        let txdata = &mut ctx.accounts.tx_data;

        // New expiry must be strictly greater than current (prevent no-op or shortening)
        require!(
            new_expires_slot > txdata.expires_slot,
            PAError::TxDataExtendMustIncrease
        );

        let old_expires = txdata.expires_slot;
        txdata.expires_slot = new_expires_slot;

        msg!(
            "TxData extended: upload_id={}, old_expires={}, new_expires={}",
            upload_id,
            old_expires,
            new_expires_slot
        );
        Ok(())
    }

    /// Close an expired TxData account. Anyone can call; rent goes to `refund`.
    pub fn txdata_close_expired(
        ctx: Context<TxDataCloseExpired>,
        upload_id: u64,
        _authority: Pubkey,
    ) -> Result<()> {
        let clock = Clock::get()?;
        let txdata = &ctx.accounts.tx_data;

        require!(clock.slot > txdata.expires_slot, PAError::TxDataNotExpired);

        msg!(
            "Expired TxData closed: upload_id={}, expires_slot={}, current_slot={}",
            upload_id,
            txdata.expires_slot,
            clock.slot
        );
        Ok(())
    }

    /// Update TxData expiry configuration (authority only).
    pub fn update_expiry_config(
        ctx: Context<UpdateExpiryConfig>,
        new_min_expiry_slots: u64,
        new_max_expiry_slots: u64,
    ) -> Result<()> {
        require!(
            new_min_expiry_slots < new_max_expiry_slots,
            PAError::InvalidExpiryConfig
        );
        require!(
            new_min_expiry_slots >= MIN_ALLOWED_EXPIRY,
            PAError::InvalidExpiryConfig
        );
        require!(
            new_max_expiry_slots <= SEVEN_DAYS_SLOTS,
            PAError::InvalidExpiryConfig
        );

        let state = &mut ctx.accounts.pa_state;
        let old_min = state.min_expiry_slots;
        let old_max = state.max_expiry_slots;

        state.min_expiry_slots = new_min_expiry_slots;
        state.max_expiry_slots = new_max_expiry_slots;

        msg!(
            "Expiry config updated: min {} -> {}, max {} -> {}",
            old_min,
            new_min_expiry_slots,
            old_max,
            new_max_expiry_slots
        );
        Ok(())
    }

    /// Execute settlement from a TxData account.
    pub fn settle_from_txdata<'info>(
        ctx: Context<'info, SettleFromTxData<'info>>,
        _upload_id: u64,
    ) -> Result<()> {
        require!(!ctx.accounts.pa_state.paused, PAError::EnforcedPause);

        let txdata = &ctx.accounts.tx_data;

        let clock = Clock::get()?;
        require!(clock.slot <= txdata.expires_slot, PAError::TxDataExpired);

        let tx: Transaction = bincode::deserialize(&txdata.payload[..txdata.written_len as usize])
            .map_err(|_| error!(PAError::InvalidTransactionData))?;

        let pa_state_info = ctx.accounts.pa_state.to_account_info();
        let payer = ctx.accounts.authority.to_account_info();

        let events = events::EventCpi {
            authority: ctx.accounts.event_authority.to_account_info(),
        };

        execute_settlement(
            &mut ctx.accounts.pa_state,
            &tx,
            SettlementAccounts {
                pa_state: pa_state_info,
                payer,
                system_program: ctx.accounts.system_program.to_account_info(),
                new_root_marker: ctx.accounts.new_root_marker.as_deref(),
                remaining: ctx.remaining_accounts,
                verifier: VerifierAccounts {
                    router_program_id: ctx.accounts.verifier_router_program.key(),
                    router: ctx.accounts.router.to_account_info(),
                    verifier_entry: ctx.accounts.verifier_entry.to_account_info(),
                    verifier_program: ctx.accounts.verifier_program.to_account_info(),
                },
                events,
            },
        )?;

        msg!("Settlement from TxData complete");
        Ok(())
    }

    /// Pause settlement. Mirrors pa-evm's `pause()`: owner-only, refused
    /// while already paused (`EnforcedPause`), announced with `PausedEvent`.
    /// While paused, `settle` and `settle_from_txdata` refuse every
    /// transaction; nothing else is gated.
    ///
    /// A permanent shutdown is a pause followed by `renounce_ownership`, as
    /// on pa-evm: with no owner, no one can unpause or upgrade.
    /// `close_markers_batch`, which requires a paused adapter, exists only in
    /// `dev-teardown` builds (never present in production) to reclaim a
    /// development deployment's marker rent.
    pub fn pause(ctx: Context<OwnerOnly>) -> Result<()> {
        let state = &mut ctx.accounts.pa_state;
        require!(!state.paused, PAError::EnforcedPause);
        state.paused = true;
        emit_cpi!(PausedEvent {
            account: ctx.accounts.authority.key(),
        });
        Ok(())
    }

    /// Resume settlement. Mirrors pa-evm's `unpause()`: owner-only, refused
    /// while not paused (`ExpectedPause`), announced with `UnpausedEvent`.
    pub fn unpause(ctx: Context<OwnerOnly>) -> Result<()> {
        let state = &mut ctx.accounts.pa_state;
        require!(state.paused, PAError::ExpectedPause);
        state.paused = false;
        emit_cpi!(UnpausedEvent {
            account: ctx.accounts.authority.key(),
        });
        Ok(())
    }

    /// Whether the router has paused the verifier this deployment routes to.
    /// Mirrors pa-evm's `riscZeroVerifierPaused()`: read by simulation.
    pub fn risc_zero_verifier_paused(ctx: Context<VerifierPauseStatus>) -> Result<bool> {
        let state = &ctx.accounts.pa_state;
        verifier_paused(
            &ctx.accounts.verifier_entry,
            &state.verifier_router,
            state.proof_selector,
        )
    }

    /// Replace the kind-table commitment every settled aggregation instance
    /// must carry. Mirrors pa-evm's `setKindTableCommitment`: authority only,
    /// zero rejected, the change emitted. A table changes whenever a token or
    /// a circuit version is listed, and transactions proven against the
    /// previous table are rejected from this point on.
    pub fn set_kind_table_commitment(
        ctx: Context<OwnerOnly>,
        new_kind_table_commitment: [u8; 32],
    ) -> Result<()> {
        require!(
            new_kind_table_commitment != [0u8; 32],
            PAError::ZeroKindTableCommitment
        );
        ctx.accounts.pa_state.kind_table_commitment = new_kind_table_commitment;
        emit_cpi!(KindTableCommitmentUpdatedEvent {
            kind_table_commitment: new_kind_table_commitment,
        });
        Ok(())
    }

    /// Deny a logic ref: no settlement consumes or creates a resource
    /// carrying it again. Mirrors pa-evm's `denyLogicRef`: owner-only, the
    /// zero ref and a ref already denied are rejected, and a denial cannot
    /// be undone. The authority pays for the entry.
    pub fn deny_logic_ref(ctx: Context<DenyLogicRef>, logic_ref: [u8; 32]) -> Result<()> {
        require!(logic_ref != [0u8; 32], PAError::ZeroLogicRefNotAllowed);
        let state = &mut ctx.accounts.pa_state;
        require!(
            !state.is_logic_ref_denied(&logic_ref),
            PAError::LogicRefAlreadyDenied
        );
        resize_account(
            &state.to_account_info(),
            PAStateAccount::space(state.depth(), state.denied_logic_refs.len() + 1),
            &ctx.accounts.authority.to_account_info(),
            &ctx.accounts.system_program.to_account_info(),
        )?;
        state.denied_logic_refs.push(logic_ref);
        emit_cpi!(LogicRefDeniedEvent { logic_ref });
        Ok(())
    }

    /// Move the ownership to `new_owner`. Mirrors OwnableUpgradeable's
    /// `transferOwnership`: owner only, effective at once, the zero key
    /// refused (`OwnableInvalidOwner`), announced with
    /// `OwnershipTransferredEvent`.
    pub fn transfer_ownership(ctx: Context<OwnerOnly>, new_owner: Pubkey) -> Result<()> {
        require!(new_owner != Pubkey::default(), PAError::OwnableInvalidOwner);
        let previous_owner = std::mem::replace(&mut ctx.accounts.pa_state.owner, new_owner);
        emit_cpi!(OwnershipTransferredEvent {
            previous_owner,
            new_owner,
        });
        Ok(())
    }

    /// Give up the ownership for good. Mirrors OwnableUpgradeable's
    /// `renounceOwnership`: owner only; the owner becomes the zero key, so
    /// no owner-only instruction, `upgrade` included, can run again.
    pub fn renounce_ownership(ctx: Context<OwnerOnly>) -> Result<()> {
        let previous_owner = std::mem::take(&mut ctx.accounts.pa_state.owner);
        emit_cpi!(OwnershipTransferredEvent {
            previous_owner,
            new_owner: Pubkey::default(),
        });
        Ok(())
    }

    /// Replace this program's code with the code in `buffer`. Mirrors the
    /// UUPS `upgradeToAndCall` pa-evm's owner calls: owner only
    /// (`_authorizeUpgrade`), announced with `UpgradedEvent`, which names the
    /// new code by its executable hash as ERC1967's `Upgraded` names the new
    /// implementation. The buffer's authority must be the owner, who wrote
    /// it; the program hands it to its upgrade authority PDA, which signs the
    /// upgrade, and its rent goes to `spill`. The new code
    /// runs from the next slot, so a release that changes a layout ships a
    /// migration the owner runs after it.
    pub fn upgrade(ctx: Context<UpgradeProgram>) -> Result<()> {
        // The event first: the self-invocation that carries it must run this
        // code, which the loader replaces below.
        let executable_hash = upgrade::executable_hash(&ctx.accounts.buffer.try_borrow_data()?)
            .ok_or(PAError::InvalidUpgradeBuffer)?;
        emit_cpi!(UpgradedEvent { executable_hash });
        upgrade::upgrade_program(
            &crate::ID,
            ctx.bumps.upgrade_authority,
            upgrade::UpgradeAccounts {
                program_data: &ctx.accounts.program_data.to_account_info(),
                program: &ctx.accounts.upgraded_program.to_account_info(),
                buffer: &ctx.accounts.buffer.to_account_info(),
                buffer_authority: &ctx.accounts.authority.to_account_info(),
                spill: &ctx.accounts.spill.to_account_info(),
                rent: &ctx.accounts.rent.to_account_info(),
                clock: &ctx.accounts.clock.to_account_info(),
                upgrade_authority: &ctx.accounts.upgrade_authority.to_account_info(),
                loader: &ctx.accounts.bpf_loader_upgradeable.to_account_info(),
            },
        )
    }

    /// Bring a state account in the previous schema version to this one,
    /// owned by the upgrade authority that signs, and hand the program's
    /// upgrade authority to its `UPGRADE_AUTHORITY_SEED` PDA. In the previous
    /// version the upgrade authority was the owner; from this one the owner
    /// is stored and upgrades go through `upgrade`. The counterpart of the
    /// call pa-evm's owner passes to `upgradeToAndCall`: run once, after the
    /// in-place upgrade and before any other instruction, which all refuse
    /// the previous version. It parses the previous layout rather than
    /// reinterpreting its bytes, pays for the account's growth, and
    /// announces the owner as `initialize` does.
    pub fn migrate_state(ctx: Context<MigrateState>) -> Result<()> {
        let info = ctx.accounts.pa_state.to_account_info();
        require_keys_eq!(*info.owner, crate::ID, PAError::NotPreviousSchema);
        let owner = ctx.accounts.authority.key();
        let state = {
            let data = info.try_borrow_data()?;
            let body = data
                .strip_prefix(PAStateAccount::DISCRIMINATOR)
                .ok_or(PAError::NotPreviousSchema)?;
            require!(
                body.first() == Some(&PREVIOUS_SCHEMA_VERSION),
                PAError::NotPreviousSchema
            );
            PreviousPAState::deserialize(&mut &body[..])
                .map_err(|_| PAError::NotPreviousSchema)?
                .migrate(owner)
        };
        resize_account(
            &info,
            PAStateAccount::space(state.depth(), state.denied_logic_refs.len()),
            &ctx.accounts.authority.to_account_info(),
            &ctx.accounts.system_program.to_account_info(),
        )?;
        state.try_serialize(&mut &mut info.try_borrow_mut_data()?[..])?;
        upgrade::hand_upgrade_authority_to_program(
            &crate::ID,
            ctx.bumps.upgrade_authority,
            &ctx.accounts.program_data.to_account_info(),
            &ctx.accounts.authority.to_account_info(),
            &ctx.accounts.upgrade_authority.to_account_info(),
            &ctx.accounts.bpf_loader_upgradeable.to_account_info(),
        )?;
        emit_cpi!(OwnershipTransferredEvent {
            previous_owner: Pubkey::default(),
            new_owner: owner,
        });
        Ok(())
    }

    /// The release this build is. Mirrors pa-evm's `VERSION`: read from the
    /// deployed program (by simulation), it names the code an address runs,
    /// which an in-place upgrade changes.
    pub fn version(_ctx: Context<Version>) -> Result<String> {
        Ok(env!("CARGO_PKG_VERSION").to_string())
    }

    /// Close marker PDAs and reclaim their rent. Development tooling only.
    ///
    /// Deleting nullifier markers destroys replay protection, and re-initializing
    /// reuses the same `pa_state` address and therefore the same marker
    /// addresses, so previously spent nullifiers become spendable again. That is
    /// the point during development and must be impossible in production, so this
    /// instruction is absent unless `dev-teardown` is enabled.
    #[cfg(feature = "dev-teardown")]
    pub fn close_markers_batch<'info>(ctx: Context<'info, CloseMarkersBatch<'info>>) -> Result<()> {
        require!(ctx.accounts.pa_state.paused, PAError::ExpectedPause);
        let authority_info = ctx.accounts.authority.to_account_info();
        for marker in ctx.remaining_accounts {
            require!(marker.owner == &crate::ID, PAError::InvalidMarker);
            require!(marker.data_is_empty(), PAError::InvalidMarker);
            let marker_lamports = marker.lamports();
            **marker.lamports.borrow_mut() = 0;
            **authority_info.lamports.borrow_mut() = authority_info
                .lamports()
                .checked_add(marker_lamports)
                .unwrap();
            marker.assign(&anchor_lang::solana_program::system_program::ID);
        }
        msg!("Closed {} markers", ctx.remaining_accounts.len());
        Ok(())
    }

    /// Overwrite the state account's schema version. Development tooling only:
    /// lets the integration suite observe every instruction refuse a foreign
    /// version. Carries no version constraint, since like a migration it must
    /// accept one; the typed load works only because the byte flip keeps the layout.
    #[cfg(feature = "dev-teardown")]
    pub fn dev_set_schema_version(ctx: Context<DevSetSchemaVersion>, version: u8) -> Result<()> {
        ctx.accounts.pa_state.schema_version = version;
        msg!("PAState schema version set to {}", version);
        Ok(())
    }
}

/// Floor at 1 lamport because 0-lamport accounts can be garbage-collected.
fn marker_lamports(rent: &Rent) -> u64 {
    rent.minimum_balance(0).max(1)
}

/// Accounts needed for the verifier_router CPI.
struct VerifierAccounts<'info> {
    router_program_id: Pubkey,
    router: AccountInfo<'info>,
    verifier_entry: AccountInfo<'info>,
    verifier_program: AccountInfo<'info>,
}

/// Validate that an expiry slot falls within the configurable bounds.
fn validate_expiry_bounds(
    pa_state: &PAStateAccount,
    current_slot: u64,
    expires_slot: u64,
) -> Result<()> {
    let min_expires = current_slot.saturating_add(pa_state.min_expiry_slots);
    let max_expires = current_slot.saturating_add(pa_state.max_expiry_slots);
    require!(expires_slot >= min_expires, PAError::TxDataExpiryTooSoon);
    require!(expires_slot <= max_expires, PAError::TxDataExpiryTooLate);
    Ok(())
}

/// Reallocate PAState if tree growth is needed for the incoming commitments.
fn maybe_grow_account<'info>(
    pa_state_info: &AccountInfo<'info>,
    state: &PAStateAccount,
    num_commitments: usize,
    payer: &AccountInfo<'info>,
    system_program: &AccountInfo<'info>,
) -> Result<()> {
    let final_next_index = state.next_index.saturating_add(num_commitments as u64);
    let required_depth = required_depth_for_leaves(final_next_index);

    // Cap at MAX_TREE_DEPTH (append_to_tree will error if exceeded)
    let target_depth = required_depth.min(MAX_TREE_DEPTH);

    if target_depth <= state.depth() {
        return Ok(());
    }

    resize_account(
        pa_state_info,
        PAStateAccount::space(target_depth, state.denied_logic_refs.len()),
        payer,
        system_program,
    )?;
    msg!(
        "Reallocated PAState: depth {} -> {}",
        state.depth(),
        target_depth
    );
    Ok(())
}

/// Resize a program-owned account to `size`, `payer` topping up its rent
/// first. Shared with the SPL token forwarder's config migration.
pub fn resize_account<'info>(
    account: &AccountInfo<'info>,
    size: usize,
    payer: &AccountInfo<'info>,
    system_program: &AccountInfo<'info>,
) -> Result<()> {
    let minimum_balance = Rent::get()?.minimum_balance(size);
    let current_balance = account.lamports();
    if minimum_balance > current_balance {
        anchor_lang::system_program::transfer(
            CpiContext::new(
                system_program.key(),
                anchor_lang::system_program::Transfer {
                    from: payer.clone(),
                    to: account.clone(),
                },
            ),
            minimum_balance - current_balance,
        )?;
    }
    account.resize(size)?;
    Ok(())
}

/// Require every root consumed by the instance to be one the adapter accepts.
///
/// Takes `state` by shared reference on purpose: validation must not be able to
/// mutate adapter state. `execute_settlement` holds `&mut PAStateAccount` for its
/// whole body, so without this narrowing the compiler would permit a mutation here
/// and the ordering would rest on what happens to be written rather than on what
/// is allowed.
fn validate_consumed_roots(
    instance: &AggregationInstance,
    state: &PAStateAccount,
    pa_state_key: &Pubkey,
    remaining_accounts: &[AccountInfo],
) -> Result<()> {
    for root in &settle::unique_consumed_roots(instance) {
        require!(
            root::is_root_valid(state, &crate::ID, pa_state_key, root, remaining_accounts),
            PAError::NonExistingRoot
        );
    }
    Ok(())
}

/// The accounts a settlement acts on.
///
/// `remaining` layout:
///   [0..nullifier_count]  — nullifier marker PDAs (created by the settlement)
///   [nullifier_count..N]  — external call forwarder segments (program + CPI accounts),
///                           in the order the resources' calls run
///
/// Historical root marker PDAs are found by key scan, so they may appear at any index.
/// The marker for the root the settlement produces is `new_root_marker`, not part of
/// `remaining`; a settlement that creates nothing produces no root and takes no marker.
struct SettlementAccounts<'a, 'info> {
    pa_state: AccountInfo<'info>,
    payer: AccountInfo<'info>,
    system_program: AccountInfo<'info>,
    new_root_marker: Option<&'a AccountInfo<'info>>,
    remaining: &'a [AccountInfo<'info>],
    verifier: VerifierAccounts<'info>,
    events: events::EventCpi<'info>,
}

/// Shared settlement logic for both settle and settle_from_txdata, in
/// pa-evm's `_execute` order. For each action: each consumed resource's
/// nullifier is recorded, then its forwarder calls run and its payload events
/// are emitted; each created resource's commitment is appended, then its calls
/// run and its events are emitted; then the action's ActionExecuted. After
/// the actions the proofs are verified, the produced root (if any) is
/// recorded with CommitmentTreeRootAdded, and TransactionExecuted closes the
/// settlement. The checks that need no state change (the instance's shape,
/// keys, kind table, denylist, duplicate nullifiers and consumed roots) run
/// first: roots are checked against the tree as it stood before the
/// transaction, as pa-evm's root set does not change until the end.
fn execute_settlement(
    state: &mut PAStateAccount,
    tx: &Transaction,
    accounts: SettlementAccounts<'_, '_>,
) -> Result<()> {
    let pa_state_key = accounts.pa_state.key;
    let events = &accounts.events;

    // The instance is the only proof-backed source of settlement data;
    // `require_aggregation` also rejects the ambiguous shape carrying both
    // base actions and an aggregation.
    let aggregation = tx
        .aggregation
        .as_ref()
        .ok_or_else(|| error!(PAError::AggregationRequired))?;
    let instance = arm_solana::journal::require_aggregation(tx).map_err(PAError::from)?;

    // A witness delta is prover-side private data; settling it would both
    // leak it on-chain and prove nothing. Reject before any other work.
    let delta_proof = match &tx.delta_proof {
        Delta::Proof(proof) => proof,
        Delta::Witness(_) => return Err(error!(PAError::ExpectedDeltaProof)),
    };

    require!(
        !instance.actions.is_empty(),
        PAError::InvalidTransactionData
    );

    // The aggregation guest verifies compliance proofs against whatever
    // compliance key the prover supplied; pinning it here is what ties the
    // settlement to *the* compliance circuit.
    require!(
        instance.compliance_key == arm_core::constants::COMPLIANCE_VK,
        PAError::ComplianceKeyMismatch
    );
    require!(
        instance.kind_table_commitment == arm_core::Digest::from_bytes(state.kind_table_commitment),
        PAError::KindTableCommitmentMismatch
    );
    // pa-evm refuses every consumed and created resource carrying a denied
    // logic ref.
    for action in &instance.actions {
        for resource in settle::action_resources(action) {
            require!(
                !state.is_logic_ref_denied(&resource.logic_ref.into()),
                PAError::DeniedLogicRef
            );
        }
    }
    instance
        .nf_duplication_check()
        .map_err(|_| error!(PAError::NullifierDuplication))?;

    validate_consumed_roots(instance, state, pa_state_key, accounts.remaining)?;

    let nullifier_count = settle::nullifier_count(instance);
    let mut nullifier_markers = accounts
        .remaining
        .get(..nullifier_count)
        .ok_or(PAError::InvalidTransactionData)?
        .iter();
    #[cfg(not(test))]
    let mut forwarder_segments =
        external_calls::ForwarderSegments::new(accounts.remaining, nullifier_count)?;

    let created_count = settle::commitment_count(instance);
    maybe_grow_account(
        &accounts.pa_state,
        state,
        created_count,
        &accounts.payer,
        &accounts.system_program,
    )?;

    let ml = marker_lamports(&Rent::get()?);

    for action in &instance.actions {
        let mut executed = ActionExecutedEvent {
            action_tree_root: action.action_tree_root.into(),
            nullifiers: Vec::with_capacity(action.consumed_publics.len()),
            consumed_logic_refs: Vec::with_capacity(action.consumed_publics.len()),
            commitments: Vec::with_capacity(action.created_publics.len()),
            created_logic_refs: Vec::with_capacity(action.created_publics.len()),
        };
        for resource in settle::action_resources(action) {
            if resource.is_consumed {
                let marker = nullifier_markers
                    .next()
                    .ok_or(PAError::InvalidTransactionData)?;
                nullifier::check_and_create_nullifier_marker(
                    &crate::ID,
                    pa_state_key,
                    &resource.tag.into(),
                    &accounts.payer,
                    marker,
                    &accounts.system_program,
                    ml,
                )?;
                executed.nullifiers.push(resource.tag.into());
                executed.consumed_logic_refs.push(resource.logic_ref.into());
            } else {
                append_to_tree(state, resource.tag)?;
                executed.commitments.push(resource.tag.into());
                executed.created_logic_refs.push(resource.logic_ref.into());
            }

            #[cfg(not(test))]
            for event in forwarder_segments
                .execute(&resource.logic_ref, resource.app_data)
                .map_err(anchor_lang::error::Error::from)?
            {
                events.emit(&event)?;
            }
            emit_app_data_events(events, &resource.tag, resource.app_data)?;
        }

        events.emit(&executed)?;
    }

    let prepared = prepare_proof_for_verification(aggregation, state.proof_selector)
        .map_err(|e| -> anchor_lang::error::Error { e.into() })?;

    msg!("Verifying aggregated proof via verifier_router");
    {
        let verifier = &accounts.verifier;
        let cpi_accounts = verifier_router::cpi::accounts::Verify {
            router: verifier.router.clone(),
            verifier_entry: verifier.verifier_entry.clone(),
            verifier_program: verifier.verifier_program.clone(),
            system_program: accounts.system_program.clone(),
        };
        let cpi_ctx = CpiContext::new(verifier.router_program_id, cpi_accounts);
        verifier_router::cpi::verify(
            cpi_ctx,
            prepared.seal,
            prepared.image_id,
            prepared.journal_digest,
        )
        .map_err(|_| error!(PAError::VerifierRouterFailed))?;
    }

    arm_solana::delta::verify_delta_proof_with_instance(delta_proof, instance)
        .map_err(PAError::from)?;

    // A transaction that creates nothing leaves the tree, and so its latest
    // root, untouched: there is no new root to record, as pa-evm adds no root
    // when none was produced. Every settlement that appends commitments
    // retains its resulting root so that concurrently constructed
    // transactions stay valid as the tree advances; Solana cannot create an
    // undeclared account, so the marker is required then.
    if created_count == 0 {
        require!(accounts.new_root_marker.is_none(), PAError::RootPdaMismatch);
    } else {
        let new_root = state.root;
        let new_root_marker = accounts.new_root_marker.ok_or(PAError::RootPdaMismatch)?;
        root::create_root_marker(
            &crate::ID,
            pa_state_key,
            &new_root,
            &accounts.payer,
            new_root_marker,
            &accounts.system_program,
            ml,
        )?;
        events.emit(&CommitmentTreeRootAddedEvent { root: new_root })?;
    }

    events.emit(&TransactionExecutedEvent {
        transaction_id: arm_solana::delta::compute_delta_msg_hash(
            &arm_solana::delta::collect_roots(instance),
        ),
    })?;
    Ok(())
}

#[event_cpi]
#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = payer,
        space = PAStateAccount::INITIAL_SPACE, // Variable-depth tree starts at depth 1
        seeds = [PA_STATE_SEED],
        bump
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(mut)]
    pub payer: Signer<'info>,

    pub system_program: Program<'info, System>,

    /// This program's ProgramData, where the loader records the upgrade
    /// authority: the deployer, who alone initializes the adapter and hands
    /// the authority to `upgrade_authority`.
    #[account(
        mut,
        address = PROGRAM_DATA @ PAError::Unauthorized,
        constraint = program_data.upgrade_authority_address == Some(payer.key())
            @ PAError::Unauthorized
    )]
    pub program_data: Account<'info, ProgramData>,

    /// CHECK: The PDA that becomes the program's upgrade authority; the
    /// seeds pin it.
    #[account(seeds = [UPGRADE_AUTHORITY_SEED], bump)]
    pub upgrade_authority: UncheckedAccount<'info>,

    /// CHECK: The upgradeable loader, which the address pins.
    #[account(address = anchor_lang::solana_program::bpf_loader_upgradeable::ID)]
    pub bpf_loader_upgradeable: UncheckedAccount<'info>,

    /// CHECK: The handler requires the router's verifier entry for the
    /// initialized selector (`verifier_paused`).
    pub verifier_entry: UncheckedAccount<'info>,
}

/// The accounts of an instruction only the owner may call, as pa-evm's
/// `onlyOwner`.
#[event_cpi]
#[derive(Accounts)]
pub struct OwnerOnly<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(constraint = authority.key() == pa_state.owner @ PAError::OwnableUnauthorizedAccount)]
    pub authority: Signer<'info>,
}

#[event_cpi]
#[derive(Accounts)]
pub struct UpgradeProgram<'info> {
    #[account(
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(constraint = authority.key() == pa_state.owner @ PAError::OwnableUnauthorizedAccount)]
    pub authority: Signer<'info>,

    /// CHECK: This program's ProgramData, which the loader rewrites; the
    /// address pins it.
    #[account(mut, address = PROGRAM_DATA)]
    pub program_data: UncheckedAccount<'info>,

    /// CHECK: This program's account, which the loader requires writable;
    /// the address pins it.
    #[account(mut, address = crate::ID)]
    pub upgraded_program: UncheckedAccount<'info>,

    /// CHECK: The loader buffer holding the new code, whose authority the
    /// loader requires to be the owner, who signs; `executable_hash` refuses
    /// any other account.
    #[account(mut)]
    pub buffer: UncheckedAccount<'info>,

    /// CHECK: Receives the buffer's rent; any account.
    #[account(mut)]
    pub spill: UncheckedAccount<'info>,

    /// CHECK: The program's upgrade authority PDA, which signs the upgrade;
    /// the seeds pin it.
    #[account(seeds = [UPGRADE_AUTHORITY_SEED], bump)]
    pub upgrade_authority: UncheckedAccount<'info>,

    pub rent: Sysvar<'info, Rent>,
    pub clock: Sysvar<'info, Clock>,

    /// CHECK: The upgradeable loader, which the address pins.
    #[account(address = anchor_lang::solana_program::bpf_loader_upgradeable::ID)]
    pub bpf_loader_upgradeable: UncheckedAccount<'info>,
}

#[event_cpi]
#[derive(Accounts)]
pub struct MigrateState<'info> {
    /// The upgrade authority, the owner in the previous schema version,
    /// which pays for the account's growth and becomes the stored owner.
    #[account(mut)]
    pub authority: Signer<'info>,

    /// CHECK: The seeds pin the address; the handler requires this program
    /// as owner and the previous schema's layout, which the typed account
    /// cannot read.
    #[account(mut, seeds = [PA_STATE_SEED], bump)]
    pub pa_state: UncheckedAccount<'info>,

    pub system_program: Program<'info, System>,

    /// This program's ProgramData, where the loader records the upgrade
    /// authority, which the handler hands to `upgrade_authority`.
    #[account(
        mut,
        address = PROGRAM_DATA @ PAError::Unauthorized,
        constraint = program_data.upgrade_authority_address == Some(authority.key())
            @ PAError::Unauthorized
    )]
    pub program_data: Account<'info, ProgramData>,

    /// CHECK: The PDA that becomes the program's upgrade authority; the
    /// seeds pin it.
    #[account(seeds = [UPGRADE_AUTHORITY_SEED], bump)]
    pub upgrade_authority: UncheckedAccount<'info>,

    /// CHECK: The upgradeable loader, which the address pins.
    #[account(address = anchor_lang::solana_program::bpf_loader_upgradeable::ID)]
    pub bpf_loader_upgradeable: UncheckedAccount<'info>,
}

#[event_cpi]
#[derive(Accounts)]
pub struct DenyLogicRef<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    /// The owner, which pays for the denylist's growth.
    #[account(
        mut,
        constraint = authority.key() == pa_state.owner @ PAError::OwnableUnauthorizedAccount
    )]
    pub authority: Signer<'info>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct Version {}

#[derive(Accounts)]
pub struct VerifierPauseStatus<'info> {
    #[account(
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    /// CHECK: The handler requires the router's verifier entry for the
    /// deployment's selector (`verifier_paused`).
    pub verifier_entry: UncheckedAccount<'info>,
}

#[event_cpi]
#[derive(Accounts)]
pub struct Settle<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(mut)]
    pub payer: Signer<'info>,
    pub system_program: Program<'info, System>,

    /// CHECK: Validated at runtime against the root produced by this settlement.
    /// Cannot use a seeds constraint: the address depends on the resulting root,
    /// which is only known after commitments are appended. Absent when the
    /// settlement creates nothing and so produces no root.
    #[account(mut)]
    pub new_root_marker: Option<UncheckedAccount<'info>>,

    /// CHECK: Validated against verifier_router stored in PAStateAccount.
    #[account(constraint = verifier_router_program.key() == pa_state.verifier_router @ PAError::VerifierRouterFailed)]
    pub verifier_router_program: UncheckedAccount<'info>,

    /// CHECK: Router state PDA - validated by verifier_router during CPI.
    pub router: UncheckedAccount<'info>,

    /// CHECK: Verifier entry PDA - validated by verifier_router during CPI.
    pub verifier_entry: UncheckedAccount<'info>,

    /// CHECK: The groth16 verifier program - validated by verifier_router.
    pub verifier_program: UncheckedAccount<'info>,
}

#[event_cpi]
#[derive(Accounts)]
#[instruction(upload_id: u64)]
pub struct SettleFromTxData<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        has_one = authority @ PAError::Unauthorized
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    #[account(mut)]
    pub authority: Signer<'info>,
    pub system_program: Program<'info, System>,

    /// CHECK: Validated at runtime against the root produced by this settlement.
    /// Cannot use a seeds constraint: the address depends on the resulting root,
    /// which is only known after commitments are appended. Absent when the
    /// settlement creates nothing and so produces no root.
    #[account(mut)]
    pub new_root_marker: Option<UncheckedAccount<'info>>,

    /// CHECK: Validated against verifier_router stored in PAStateAccount.
    #[account(constraint = verifier_router_program.key() == pa_state.verifier_router @ PAError::VerifierRouterFailed)]
    pub verifier_router_program: UncheckedAccount<'info>,

    /// CHECK: Router state PDA - validated by verifier_router during CPI.
    pub router: UncheckedAccount<'info>,

    /// CHECK: Verifier entry PDA - validated by verifier_router during CPI.
    pub verifier_entry: UncheckedAccount<'info>,

    /// CHECK: The groth16 verifier program - validated by verifier_router.
    pub verifier_program: UncheckedAccount<'info>,
    // remaining_accounts: nullifier PDAs + external call accounts
}

#[derive(Accounts)]
#[instruction(upload_id: u64, capacity: u32)]
pub struct TxDataInit<'info> {
    /// PAState for reading configurable expiry bounds.
    #[account(
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(
        init,
        payer = authority,
        space = TxDataAccount::space(capacity as usize),
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    #[account(mut)]
    pub authority: Signer<'info>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(upload_id: u64)]
pub struct TxDataWrite<'info> {
    #[account(
        mut,
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        has_one = authority @ PAError::Unauthorized
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    pub authority: Signer<'info>,
}

#[derive(Accounts)]
#[instruction(upload_id: u64)]
pub struct TxDataClose<'info> {
    #[account(
        mut,
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        has_one = authority @ PAError::Unauthorized,
        close = refund
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    pub authority: Signer<'info>,

    /// CHECK: Receives the rent refund. Must match tx_data.refund.
    #[account(mut, address = tx_data.refund)]
    pub refund: UncheckedAccount<'info>,
}

#[derive(Accounts)]
#[instruction(upload_id: u64)]
pub struct TxDataExtend<'info> {
    /// PAState for reading configurable expiry bounds.
    #[account(
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(
        mut,
        seeds = [TX_DATA_SEED, authority.key().as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        has_one = authority @ PAError::Unauthorized
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    pub authority: Signer<'info>,
}

#[derive(Accounts)]
#[instruction(upload_id: u64, authority: Pubkey)]
pub struct TxDataCloseExpired<'info> {
    #[account(
        mut,
        seeds = [TX_DATA_SEED, authority.as_ref(), &upload_id.to_le_bytes()],
        bump = tx_data.bump,
        close = refund
    )]
    pub tx_data: Account<'info, TxDataAccount>,

    /// Anyone can call, pays tx fee.
    pub payer: Signer<'info>,

    /// CHECK: Receives the rent refund. Must match tx_data.refund.
    #[account(mut, address = tx_data.refund)]
    pub refund: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct UpdateExpiryConfig<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(constraint = authority.key() == pa_state.owner @ PAError::OwnableUnauthorizedAccount)]
    pub authority: Signer<'info>,
}

#[cfg(feature = "dev-teardown")]
#[derive(Accounts)]
pub struct CloseMarkersBatch<'info> {
    #[account(
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
        constraint = pa_state.schema_version == SCHEMA_VERSION
            @ PAError::UnsupportedStateSchema,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(
        mut,
        constraint = authority.key() == pa_state.owner @ PAError::OwnableUnauthorizedAccount
    )]
    pub authority: Signer<'info>,
}

#[cfg(feature = "dev-teardown")]
#[derive(Accounts)]
pub struct DevSetSchemaVersion<'info> {
    #[account(
        mut,
        seeds = [PA_STATE_SEED],
        bump = pa_state.bump,
    )]
    pub pa_state: Account<'info, PAStateAccount>,

    #[account(constraint = authority.key() == pa_state.owner @ PAError::OwnableUnauthorizedAccount)]
    pub authority: Signer<'info>,
}

// Four separate event structs with identical fields: each produces a distinct Anchor
// discriminator (sha256 of the struct name), enabling indexers to filter by payload
// category at the log-parsing level without decoding the event body.
#[event]
pub struct ResourcePayloadEvent {
    pub tag: [u8; 32],
    pub index: u32,
    pub blob: Vec<u8>,
}

#[event]
pub struct DiscoveryPayloadEvent {
    pub tag: [u8; 32],
    pub index: u32,
    pub blob: Vec<u8>,
}

#[event]
pub struct ExternalPayloadEvent {
    pub tag: [u8; 32],
    pub index: u32,
    pub blob: Vec<u8>,
}

#[event]
pub struct ApplicationPayloadEvent {
    pub tag: [u8; 32],
    pub index: u32,
    pub blob: Vec<u8>,
}

/// Mirrors pa-evm: `event KindTableCommitmentUpdated(bytes32 kindTableCommitment);`
#[event]
pub struct KindTableCommitmentUpdatedEvent {
    pub kind_table_commitment: [u8; 32],
}

/// Mirrors OpenZeppelin Pausable: `event Paused(address account);`
#[event]
pub struct PausedEvent {
    pub account: Pubkey,
}

/// Mirrors OpenZeppelin Pausable: `event Unpaused(address account);`
#[event]
pub struct UnpausedEvent {
    pub account: Pubkey,
}

/// Mirrors OpenZeppelin Ownable: `event OwnershipTransferred(address indexed
/// previousOwner, address indexed newOwner);`. The zero key stands for no
/// owner: the previous owner when `initialize` or `migrate_state` sets the
/// first one, the new owner when `renounce_ownership` gives it up.
#[event]
pub struct OwnershipTransferredEvent {
    pub previous_owner: Pubkey,
    pub new_owner: Pubkey,
}

/// Mirrors ERC1967: `event Upgraded(address indexed implementation);`. A
/// Solana program keeps its address across upgrades, so the new code is
/// named by its executable hash: sha256 of the code without trailing zero
/// bytes, which `solana-verify get-program-hash` reports for the deployed
/// program.
#[event]
pub struct UpgradedEvent {
    pub executable_hash: [u8; 32],
}

/// Mirrors pa-evm: `event CommitmentTreeRootAdded(bytes32 root);`: the
/// empty tree's root at initialization, then the root each settlement that
/// appends commitments produces.
#[event]
pub struct CommitmentTreeRootAddedEvent {
    pub root: [u8; 32],
}

/// Mirrors pa-evm: `event LogicRefDenied(bytes32 indexed logicRef);`
#[event]
pub struct LogicRefDeniedEvent {
    pub logic_ref: [u8; 32],
}

/// Mirrors pa-evm: `event ActionExecuted(bytes32 actionTreeRoot,
/// bytes32[] nullifiers, bytes32[] consumedLogicRefs, bytes32[] commitments,
/// bytes32[] createdLogicRefs);`. The commitments are appended to the tree in
/// the order listed, action after action.
#[event]
pub struct ActionExecutedEvent {
    pub action_tree_root: [u8; 32],
    pub nullifiers: Vec<[u8; 32]>,
    pub consumed_logic_refs: Vec<[u8; 32]>,
    pub commitments: Vec<[u8; 32]>,
    pub created_logic_refs: Vec<[u8; 32]>,
}

/// Mirrors pa-evm: `event TransactionExecuted(bytes32 indexed transactionId);`,
/// the Keccak-256 hash of the concatenated action tree roots: the message the
/// delta proof signs, unique per transaction and known to the sender before
/// submission.
#[event]
pub struct TransactionExecutedEvent {
    pub transaction_id: [u8; 32],
}

/// Matches EVM PA's ForwarderCallExecuted event.
#[event]
pub struct ForwarderCallExecutedEvent {
    pub forwarder: Pubkey,
    pub input: Vec<u8>,
    pub output: Vec<u8>,
}

/// Whether the router has emergency-stopped the verifier it routes
/// `selector` to: the `estopped` flag of the router's verifier entry
/// `["verifier", selector]`, as pa-evm's `riscZeroVerifierPaused()` asks the
/// router. Any other account is refused.
fn verifier_paused(entry: &AccountInfo, router: &Pubkey, selector: [u8; 4]) -> Result<bool> {
    let (expected, _) = Pubkey::find_program_address(&[b"verifier", &selector], router);
    require_keys_eq!(*entry.key, expected, PAError::InvalidVerifierEntry);
    require_keys_eq!(*entry.owner, *router, PAError::InvalidVerifierEntry);
    let data = entry.try_borrow_data()?;
    let entry = verifier_router::accounts::VerifierEntry::try_deserialize(&mut &data[..])
        .map_err(|_| error!(PAError::InvalidVerifierEntry))?;
    Ok(entry.estopped)
}

fn emit_app_data_events(
    events: &events::EventCpi,
    tag: &arm_core::Digest,
    app_data: &arm_core::logic_instance::AppData,
) -> Result<()> {
    let tag_bytes: [u8; 32] = (*tag).into();

    macro_rules! emit_payloads {
        ($payloads:expr, $Event:ident) => {
            for (i, payload) in $payloads.iter().enumerate() {
                if payload.deletion_criterion == DELETION_CRITERION_NEVER {
                    events.emit(&$Event {
                        tag: tag_bytes,
                        index: i as u32,
                        blob: arm_core::utils::words_to_bytes(&payload.blob).to_vec(),
                    })?;
                }
            }
        };
    }

    emit_payloads!(app_data.resource_payload, ResourcePayloadEvent);
    emit_payloads!(app_data.discovery_payload, DiscoveryPayloadEvent);
    emit_payloads!(app_data.external_payload, ExternalPayloadEvent);
    emit_payloads!(app_data.application_payload, ApplicationPayloadEvent);
    Ok(())
}
