[package]
name = "fixture-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
arm = { git = "https://github.com/anoma/arm-risc0", rev = "3da9a640ed8f733dce6a082f1043ef9571ad1bdf", package = "arm", features = ["aggregation", "solana"] }
arm-test-app = {  git = "https://github.com/anoma/arm-risc0", rev = "3da9a640ed8f733dce6a082f1043ef9571ad1bdf", package = "arm-test-app"}
base64 = "0.22"
bincode = "1.3.3"
hex = "0.4"
k256 = "=0.13.3"
rayon = "1.10"
risc0-zkvm = "3.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[workspace]
