[package]
name = "passthrough-logic-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "3.0.3", features = ["std", "unstable"], default-features = false }
arm = { git = "https://github.com/anoma/arm-risc0", rev = "3da9a640ed8f733dce6a082f1043ef9571ad1bdf", package = "arm", default-features = false }

