[features]
resolution = true
skip-lint = false

[programs.devnet]
block_time_forwarder = "3mesRGxMv9wRB1xp7X4uxbf7GwnQC9PpHSJyCzcXwrsf"
mock_verifier = "H3ZFoDHFvthGZu3kxpif3oSWm8MQn8uKvgDhrvVVHvHf"
protocol_adapter = "5zeqkB3kc9fd1RvaXB2GeMB53Jgf98QJtaFK38e6tTsc"
spl_token_forwarder = "BsfuXpxw8oCmZXnYijyQkUYNcCnuskFZbYizmWLnpSU7"
test_forwarder = "QfyNAtiNrw1YJAm9FzShw6oVZ4BDHojKrpje2mNNctD"

[programs.localnet]
block_time_forwarder = "3mesRGxMv9wRB1xp7X4uxbf7GwnQC9PpHSJyCzcXwrsf"
mock_verifier = "H3ZFoDHFvthGZu3kxpif3oSWm8MQn8uKvgDhrvVVHvHf"
protocol_adapter = "5zeqkB3kc9fd1RvaXB2GeMB53Jgf98QJtaFK38e6tTsc"
spl_token_forwarder = "BsfuXpxw8oCmZXnYijyQkUYNcCnuskFZbYizmWLnpSU7"
test_forwarder = "QfyNAtiNrw1YJAm9FzShw6oVZ4BDHojKrpje2mNNctD"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
