[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
block_time_forwarder = "FLh2rbnAbtFZkLMMX36Fh4rV9wJWUFrLw5gDmoLzPEgq"
solana_pa_prototype = "AV1dFJCfq6CmJ523ft8YwNsQVYEoDxzNfEhEFJzoUkjt"

[programs.localnet]
block_time_forwarder = "FLh2rbnAbtFZkLMMX36Fh4rV9wJWUFrLw5gDmoLzPEgq"
solana_pa_prototype = "AV1dFJCfq6CmJ523ft8YwNsQVYEoDxzNfEhEFJzoUkjt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/workspace/solana-pa-prototype/scripts/devnet-wallet.json"

[scripts]
test = "bash -lc './scripts/deploy-groth16-verifier.sh && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts'"
